"""Regression tests: Python port vs. values produced by the original MATLAB code.

Reference file is generated by tools/gen_reference_hydrofrac.m (MATLAB R2024a+).
"""
import json
from pathlib import Path

import numpy as np
import pytest

from geomech.core import hydrofrac as hf

REF = Path(__file__).parent / "reference" / "hydrofrac_matlab.json"


def _load_cases():
    if not REF.exists():
        return []
    return json.loads(REF.read_text())


def _params(case):
    p = case["params"]
    return hf.FracParams(E=p["E"], nu=p["nu"], Q=p["Q"], mu=p["mu"],
                         C=p["C"], Sp=p["Sp"], h=p["h"])


_CASES = _load_cases()
_IDS = [f"{c['model']}-leakoff{c['leakoff']}" for c in _CASES]
needs_ref = pytest.mark.skipif(not _CASES, reason="MATLAB reference missing; run tools/gen_reference_hydrofrac.m")


@needs_ref
@pytest.mark.parametrize("case", _CASES, ids=_IDS)
def test_simulate_matches_matlab(case):
    res = hf.simulate(case["model"], _params(case), case["params"]["t_f"])
    np.testing.assert_allclose(res.t, case["t"], rtol=1e-12)
    np.testing.assert_allclose(res.length, case["L"], rtol=1e-8)
    np.testing.assert_allclose(res.w_max, case["Wmax"], rtol=1e-8)
    np.testing.assert_allclose(res.w_avg, case["Wbar"], rtol=1e-8)
    np.testing.assert_allclose(res.p_net, case["Pnet"], rtol=1e-8)
    np.testing.assert_allclose(res.volume, case["V"], rtol=1e-12)


@needs_ref
@pytest.mark.parametrize("case", _CASES, ids=_IDS)
def test_evaluate_matches_series_endpoint(case):
    single = hf.evaluate(case["model"], _params(case), case["params"]["t_f"])
    assert single.length == pytest.approx(case["L"][-1], rel=1e-8)
    assert single.w_max == pytest.approx(case["Wmax"][-1], rel=1e-8)
    assert single.p_net == pytest.approx(case["Pnet"][-1], rel=1e-8)


def test_aperture_profile_shapes():
    x, w = hf.aperture_profile("PKN", 100.0, 0.01)
    assert x[0] == 0 and x[-1] == 100 and w[0] == pytest.approx(0.01) and w[-1] == 0
    _, w = hf.aperture_profile("KGD", 100.0, 0.01)
    assert w[-1] == 0
    _, w = hf.aperture_profile("radial", 100.0, 0.01)
    assert w[-1] == 0


def test_meshes_are_finite_and_shaped():
    m = hf.pkn_mesh(30, 100, 0.1, 0.01)
    assert m.X.shape == (51, 51) and np.isfinite(m.Y).all()
    m = hf.kgd_mesh(30, 100, 0.1, 0.01)
    assert m.X.shape == (2, 51) and np.isfinite(m.Y).all()
    m = hf.radial_mesh(100, 0.1, 0.01)
    assert m.X.shape == (73, 51) and np.isfinite(m.Z).all()


def test_radial_requires_leakoff():
    with pytest.raises(ValueError):
        hf.evaluate("radial", hf.FracParams(E=20e9, nu=0.25, Q=0.05, mu=0.1), 100.0)
