% AUTO-GENERATED by tools/make_reference_stereonet_m.py - do not edit.
% Run from repo root:  matlab -batch "run('tools/gen_reference_stereonet.m')"
root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(root, 'src'));
D = dlmread(fullfile(root, 'src', 'stereo_exmapledata', 'exampleData.txt'), '\t', 1, 0);
jData = num2cell(D);
out = struct(); out.data = D;
combos = [0 0; 0 1; 1 0; 1 1];   % upper, equalAngle
for k = 1:4
    upper = combos(k,1); equalAngle = combos(k,2);
    tre = D(:,2)*pi/180 + pi; plu = 0.5*pi - D(:,1)*pi/180;
    [x, y] = convert_TPCoor(tre', plu', upper, equalAngle);
    out.proj(k).upper = upper; out.proj(k).equalAngle = equalAngle; out.proj(k).x = x(:)'; out.proj(k).y = y(:)';
    [cx, cy, res] = sp_contour(jData, upper, equalAngle);
    out.proj(k).cx = cx; out.proj(k).cy = cy; out.proj(k).density = res;
    fprintf('proj %d: density max %.3f\n', k, max(res(:)));
end
% convert_VecTP on the pole vectors of the data (as in FCM_Callback)
tre = D(:,2) + 180; tre(tre >= 360) = tre(tre >= 360) - 360; plu = 90 - D(:,1); plu(plu < 0) = plu(plu < 0) + 360;
V = [cos(plu/180*pi).*cos(tre/180*pi), cos(plu/180*pi).*sin(tre/180*pi), sin(plu/180*pi)];
[vt, vp] = convert_VecTP(V(:,1), V(:,2), V(:,3));
out.vec = V; out.vec_tre = vt(:)'; out.vec_plu = vp(:)';
% great circles (wulffCircle geometry) for 5 planes, lower and upper
P = [30 45; 60 120; 85 200; 10 300; 45 0];
for i = 1:5
    for upper = 0:1
        [gx, gy] = sp_wulff(P(i,1)*pi/180, P(i,2)*pi/180, upper);
        out.gc(i, upper+1).dip = P(i,1); out.gc(i, upper+1).did = P(i,2); out.gc(i, upper+1).upper = upper;
        out.gc(i, upper+1).x = gx; out.gc(i, upper+1).y = gy;
    end
end
% designated-set windows: treFrom treTo pluFrom pluTo (deg)
W = [150 220 10 40; 330 30 0 30; 100 200 -20 30; 0 360 0 90];
for i = 1:size(W,1)
    [avg, n] = sp_meand(jData, W(i,1)*pi/180, W(i,2)*pi/180, W(i,3)*pi/180, W(i,4)*pi/180, 0, 0);
    out.sets(i).window = W(i,:); out.sets(i).avg = avg; out.sets(i).n = n;
    if any(isnan(avg)), out.sets(i).dip = NaN; out.sets(i).did = NaN;
    else
        [ta, pa] = convert_VecTP(avg(1), avg(2), avg(3)); di = pi/2 - pa; did = ta - pi; if did < 0, did = did + 2*pi; end
        out.sets(i).dip = di*180/pi; out.sets(i).did = did*180/pi;
    end
    fprintf('set %d: n=%d dip %.2f did %.2f\n', i, n, out.sets(i).dip, out.sets(i).did);
end
% FCM from a fixed initial partition
rng(7); U0 = initfcm(3, size(V,1));
[center, U, obj] = sp_fcm(V, U0, 3);
out.fcm.U0 = U0; out.fcm.center = center; out.fcm.U = U; out.fcm.obj = obj(:)';
fprintf('fcm: %d iterations, obj %.6f\n', numel(obj), obj(end));
% rose diagram counts
[theta] = sp_rose(D(:,2)');
f = figure('visible', 'off'); [tout, rout] = rose(theta, 36); close(f);
out.rose_theta = theta(:)'; out.rose_counts = rout(2:4:end);
fo = fullfile(root, 'tests', 'reference', 'stereonet_matlab.json');
fid = fopen(fo, 'w'); fwrite(fid, jsonencode(out), 'char'); fclose(fid);
fprintf('wrote %s\n', fo);

% =====================================================================
function [x, y, result] = sp_contour(jData, upper, equalAngle)
vec = zeros(2*size(jData,1), 3);
theta = acos(99/100);

% (GUI if removed)
    % (no GUI)
    r1 = 50;
    r2 = 100;
    result = zeros(r2,r1);

    for i=1:size(jData,1)
        tre = jData{i,2} + 180; % trend
        if tre >= 360
            tre = tre - 360;
        end
        plu = 90 - jData{i,1}; % plunge
        if plu < 0
            plu = plu + 360;
        end
        vec(2*i-1,:) = [cos(plu*pi/180)*cos(tre*pi/180) cos(plu*pi/180)*sin(tre*pi/180) sin(plu*pi/180)];
        vec(2*i,:) = [-cos(plu*pi/180)*cos(tre*pi/180) -cos(plu*pi/180)*sin(tre*pi/180) -sin(plu*pi/180)];
    end

    for i=0:(r1-1)
        for j=0:(r2-1)
            tmp = [cos(i*pi/2/(r1-1))*cos(j*2*pi/(r2-1)) cos(i*pi/2/(r1-1))*sin(j*2*pi/(r2-1)) sin(i*pi/2/(r1-1))];
            dis = sqrt(sum((vec - tmp).^2, 2));  % == dist3(vec, tmp)
            num = sum(dis <= 2*sin(theta/2));
            result(j+1,i+1) = num / size(jData,1) * 100;
        end
    end

    x = zeros(r2,r1);
    y = zeros(r2,r1);

    for i=0:(r1-1)
        for j=0:(r2-1)
            tre = j*2*pi/(r2-1);
            plu = i*pi/2/(r1-1);
            [x(j+1, i+1), y(j+1, i+1)] = convert_TPCoor(tre, plu, upper, equalAngle);
        end
    end
end

function [avg, n] = sp_meand(jData, treFrom, treTo, pluFrom, pluTo, upper, equalAngle)
    fig = figure('visible', 'off'); axes(fig); hold on;
    handles.hg.radiobutton2 = uicontrol(fig, 'style', 'radiobutton', 'Value', 0);
    handles.hg.listbox2 = uicontrol(fig, 'style', 'listbox');
    hWindow = cell(1); list_desig = [];
tmp = [];

if treFrom < treTo
    theta = treFrom:1/1000:treTo;
else
    theta = treFrom-2*pi:1/1000:treTo;
end        

if pluFrom < 0
    [x1(1), y1(1)] = convert_TPCoor(treFrom-pi, -pluFrom, upper, equalAngle);
    [x1(2), y1(2)] = convert_TPCoor(treFrom-pi, 0, upper, equalAngle);
    [x2(1), y2(1)] = convert_TPCoor(treTo-pi, -pluFrom, upper, equalAngle);
    [x2(2), y2(2)] = convert_TPCoor(treTo-pi, 0, upper, equalAngle);
    [x3(1), y3(1)] = convert_TPCoor(treFrom, pluTo, upper, equalAngle);
    [x3(2), y3(2)] = convert_TPCoor(treFrom, 0, upper, equalAngle);
    [x4(1), y4(1)] = convert_TPCoor(treTo, pluTo, upper, equalAngle);
    [x4(2), y4(2)] = convert_TPCoor(treTo, 0, upper, equalAngle);
    if size(hWindow,2) == 1
        hWindow{1} = plot(x1, y1, 'r', x2, y2, 'r', x3, y3, 'r', x4, y4, 'r');
    else
        hWindow{size(hWindow,2)+1} = plot(x1, y1, 'r', x2, y2, 'r', x3, y3, 'r', x4, y4, 'r');
    end

    [x1, y1] = convert_TPCoor(theta-pi, -pluFrom*ones(1,size(theta,2)), upper, equalAngle);
    [x2, y2] = convert_TPCoor(theta-pi, 0*ones(1,size(theta,2)), upper, equalAngle);
    [x3, y3] = convert_TPCoor(theta, pluTo*ones(1,size(theta,2)), upper, equalAngle);
    [x4, y4] = convert_TPCoor(theta, 0*ones(1,size(theta,2)), upper, equalAngle);
    hWindow{size(hWindow,2)+1} = plot(x1, y1, 'r', x2, y2, 'r', x3, y3, 'r', x4, y4, 'r');

    if isempty(list_desig) == 1
        list_desig = sprintf('%.0f%c~%.0f%c / %.0f%c~%.0f%c',treFrom*180/pi,char(176),treTo*180/pi,char(176),pluFrom*180/pi,char(176),pluTo*180/pi,char(176));
    else
        tmpc = sprintf('%.0f%c~%.0f%c / %.0f%c~%.0f%c',treFrom*180/pi,char(176),treTo*180/pi,char(176),pluFrom*180/pi,char(176),pluTo*180/pi,char(176));
        list_desig = char(list_desig,tmpc);
    end
    if get(handles.hg.radiobutton2,'Value') == 1
        set(handles.hg.listbox2,'String',list_desig);
    end
    
    for i=1:size(jData,1)
        tre = jData{i,2}*pi/180 + pi; % trend
        if tre >= 2*pi
            tre = tre - 2*pi;
        end
        if tre >= pi
            tre_sym = tre - pi;
        else
            tre_sym = tre + pi;
        end
        plu = pi/2 - jData{i,1}*pi/180; % plunge
        if plu < 0
            plu = plu + 2*pi;
        end
        
        if treFrom < treTo
            if (treFrom <= tre) && (tre <= treTo) && (plu <= pluTo)
                tmp = [tmp;cos(plu)*cos(tre), cos(plu)*sin(tre), sin(plu)];
            elseif (treFrom <= tre_sym) && (tre_sym <= treTo) && (plu <= (-pluFrom))
                tmp = [tmp;-cos(plu)*cos(tre), -cos(plu)*sin(tre), -sin(plu)];
            end
        else
            if ((treFrom <= tre) || (tre <= treTo)) && (plu <= pluTo)
                tmp = [tmp;cos(plu)*cos(tre), cos(plu)*sin(tre), sin(plu)];
            elseif ((treFrom <= tre_sym) || (tre_sym <= treTo)) && (plu <= (-pluFrom))
                tmp = [tmp;-cos(plu)*cos(tre), -cos(plu)*sin(tre), -sin(plu)];
            end
        end
    end
    avg = mean(tmp);
    avg = avg/norm(avg);
    
else
    [x1(1), y1(1)] = convert_TPCoor(treFrom, pluFrom, upper, equalAngle);
    [x1(2), y1(2)] = convert_TPCoor(treFrom, pluTo, upper, equalAngle);
    [x2(1), y2(1)] = convert_TPCoor(treTo, pluFrom, upper, equalAngle);
    [x2(2), y2(2)] = convert_TPCoor(treTo, pluTo, upper, equalAngle);
    if size(hWindow,2) == 1
        hWindow{1} = plot(x1, y1, 'r', x2, y2, 'r');
    else
        hWindow{size(hWindow,2)+1} = plot(x1, y1, 'r', x2, y2, 'r');
    end

    [x1, y1] = convert_TPCoor(theta, pluFrom*ones(1,size(theta,2)), upper, equalAngle);
    [x2, y2] = convert_TPCoor(theta, pluTo*ones(1,size(theta,2)), upper, equalAngle);
    hWindow{size(hWindow,2)+1} = plot(x1, y1, 'r', x2, y2, 'r');

    if isempty(list_desig) == 1
        list_desig = sprintf('%.0f%c~%.0f%c / %.0f%c~%.0f%c',treFrom*180/pi,char(176),treTo*180/pi,char(176),pluFrom*180/pi,char(176),pluTo*180/pi,char(176));
    else
        tmpc = sprintf('%.0f%c~%.0f%c / %.0f%c~%.0f%c',treFrom*180/pi,char(176),treTo*180/pi,char(176),pluFrom*180/pi,char(176),pluTo*180/pi,char(176));
        list_desig = char(list_desig,tmpc);
    end
    if get(handles.hg.radiobutton2,'Value') == 1
        set(handles.hg.listbox2,'String',list_desig);
    end
    
    for i=1:size(jData,1)
        tre = jData{i,2}*pi/180 +pi; % trend
        if tre > 2*pi
            tre = tre - 2*pi;
        end
        plu = pi/2 - jData{i,1}*pi/180; % plunge
        if plu < 0
            plu = plu + 2*pi;
        end
        
        if treFrom < treTo
            if (treFrom <= tre) && (tre <= treTo) && (pluFrom <= plu) && (plu <= pluTo)
                tmp = [tmp;cos(plu)*cos(tre), cos(plu)*sin(tre), sin(plu)];
            end
        else
            if ((treFrom <= tre) || (tre <= treTo)) && (pluFrom <= plu) && (plu <= pluTo)
                tmp = [tmp;cos(plu)*cos(tre), cos(plu)*sin(tre), sin(plu)];
            end
        end
    end
    
    if size(tmp,1) == 1
        avg = tmp;
    else
        avg = mean(tmp);
        avg = avg/norm(avg);
    end
end
    n = size(tmp, 1);
    close(fig);
end

function theta = sp_rose(didData)
strike(2*size(didData, 2)) = 0; % assigning the size of strike data
% for i = 1:size(didData, 2) % conversion of dip direction to strike
%     if mod(didData(i),10) == 0
%         didData(i) = didData(i)+0.01;
%     end
%     if (didData(i)>270) && (didData(i)<360)
%         strike(2*i-1) = didData(i)-90;
%         strike(2*i) = didData(i)-270;
%     elseif (didData(i)>=0) && (didData(i)<90)
%         strike(2*i-1) = didData(i)+90;
%         strike(2*i) = didData(i)+270;
%     else
%         strike(2*i-1) = didData(i)+90;
%         strike(2*i) = didData(i)-90;
%     end
% end

for i = 1:size(didData, 2)
    if mod(didData(i),10) == 0
        if didData(i) == 360
            didData(i) = didData(i)-359.999;
        else
            didData(i) = didData(i)+0.001;
        end
    end
    if (didData(i)>=270) && (didData(i)<360)
        strike(2*i-1) = didData(i)-90;
        strike(2*i) = didData(i)-270;
    elseif (didData(i)>=0) && (didData(i)<90)
        strike(2*i-1) = didData(i)+90;
        strike(2*i) = didData(i)+270;
    else
        strike(2*i-1) = didData(i)+90;
        strike(2*i) = didData(i)-90;
    end
end

theta = (90*ones(size(strike, 1),1)-strike)*pi/180;
end

function [x, y] = sp_wulff(di, did, upper)
N = 50;
psi = 0:pi/N:pi; % trend along great circle, measured from strike
adi = atan(tan(di)*sin(psi)); % apparent dip
rproj = tan((pi/2-adi)/2); % radius on the projection plane
x = rproj.*(sin(psi)*sin(did)+cos(psi)*(-cos(did)));
y = rproj.*(sin(psi)*cos(did)+cos(psi)*sin(did));
if upper == 1
    x = -x;
    y = -y;
end
end

function [center, U, obj_fcn] = sp_fcm(data, U, cluster_n)
    expo = 2; max_iter = 100; min_impro = 1e-5;
    obj_fcn = zeros(max_iter, 1);
    for i = 1:max_iter
        [U, center, obj_fcn(i)] = stepfcm_new(data, U, cluster_n, expo);
        if i > 1
            if abs(obj_fcn(i) - obj_fcn(i-1)) < min_impro, break; end
        end
    end
    obj_fcn(i+1:max_iter) = [];
end
