% AUTO-GENERATED by tools/make_reference_borehole_m.py - do not edit.
% Computational blocks of src/BSA210831_v2.m wrapped as functions, plus calUCS/calOBB.
% Run from repo root:  matlab -batch "run('tools/gen_reference_borehole.m')"
root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(root, 'src'));
out = struct();

% ---------------- single orientation, analytic ----------------
iso = [1/100 -0.25/100 -0.25/100 0 0 0; -0.25/100 1/100 -0.25/100 0 0 0; -0.25/100 -0.25/100 1/100 0 0 0; ...
       0 0 0 2*1.25/100 0 0; 0 0 0 0 2*1.25/100 0; 0 0 0 0 0 2*1.25/100];
E=60; E_=40; v=0.25; v_=0.2; G=15;
trans = [1/E -v/E -v_/E_ 0 0 0; -v/E 1/E -v_/E_ 0 0 0; -v_/E_ -v_/E_ 1/E_ 0 0 0; 0 0 0 1/G 0 0; 0 0 0 0 1/G 0; 0 0 0 0 0 2*(1+v)/E];
% cases: {Gmat, Sx, Sy, Sz, Sxy, Syz, Sxz, Pp, Pmud(or NaN), dT, alpha, Gr, polar, azimuth}
cases = {
  iso,   30, 20, 25, 0, 0, 0, 10, NaN, 0, 0, 0.1, 0, 0;
  iso,   30, 20, 25, 5, 2, 3, 10, 15,  0, 0, 0.1, 30, 45;
  iso,   30, 20, 25, 0, 0, 0, 10, 15, 20, 1e-5, 0.1, 60, 120;
  trans, 30, 20, 25, 0, 0, 0, 10, NaN, 0, 0, 0.1, 0, 0;
  trans, 30, 20, 25, 5, 2, 3, 10, 15, 20, 1e-5, 0.1, 30, 45;
};
ri = 1:10:181; ti = 1:40:721;
for k = 1:size(cases, 1)
    c = cases(k, :);
    [Sr, St, Sz, Trt, Trz, Ttz, Sp1, Sp2, Sp3, dispxx, dispyy, gridr, gridtheta, mu, lbd] = ...
        bsa_analytic(c{1}, c{2}, c{3}, c{4}, c{5}, c{6}, c{7}, c{8}, c{9}, c{10}, c{11}, c{12}, c{13}, c{14});
    out.analytic(k).inputs = c(2:14);
    out.analytic(k).Gmat = c{1};
    out.analytic(k).ri = ri - 1; out.analytic(k).ti = ti - 1;
    out.analytic(k).r = gridr(ri, ti); out.analytic(k).theta = gridtheta(ri, ti);
    out.analytic(k).Sr = Sr(ri, ti); out.analytic(k).St = St(ri, ti); out.analytic(k).Sz = Sz(ri, ti);
    out.analytic(k).Trt = Trt(ri, ti); out.analytic(k).Trz = Trz(ri, ti); out.analytic(k).Ttz = Ttz(ri, ti);
    out.analytic(k).Sp1 = Sp1(ri, ti); out.analytic(k).Sp2 = Sp2(ri, ti); out.analytic(k).Sp3 = Sp3(ri, ti);
    out.analytic(k).dispxx = dispxx(ri, ti); out.analytic(k).dispyy = dispyy(ri, ti);
    out.analytic(k).mu_re = real(mu); out.analytic(k).mu_im = imag(mu);
    out.analytic(k).St_wall = St(1, :);   % full wall profile for breakout geometry
    out.analytic(k).Sp1_wall = Sp1(1, :); out.analytic(k).Sp3_wall = Sp3(1, :);
    % breakout geometry with UCS = 40 MPa, friction 30 deg
    [rbbo, thetabbo] = bsa_bbo(40e6, 30*pi/180, gridtheta, gridr, Sp1, Sp3);
    out.analytic(k).rbbo = rbbo; out.analytic(k).thetabbo = thetabbo;
    fprintf('analytic %d: St wall max %.4f MPa, rbbo %.4f, thetabbo %.2f\n', k, max(St(1,:))/1e6, rbbo, thetabbo*180/pi);
end

% ---------------- single orientation, FEM (small mesh) ----------------
[srr, stt, srt, xe, ye] = bsa_fem(iso, 30, 20, 25, 5, 0, 0, 10, 15, 0, 0, 0.1, 0, 0, 16, 16);
out.fem.inputs = {30, 20, 25, 5, 0, 0, 10, 15, 0, 0, 0.1, 0, 0}; out.fem.rmesh = 16; out.fem.thmesh = 16;
out.fem.srr = srr(:)'; out.fem.stt = stt(:)'; out.fem.srt = srt(:)'; out.fem.xe = xe(:)'; out.fem.ye = ye(:)';
fprintf('fem: stt range %.4f .. %.4f MPa\n', min(stt)/1e6, max(stt)/1e6);

% ---------------- all orientations (calUCS / calOBB) ----------------
E = 100; v = 0.25;
Gmat=[1/E -v/E -v/E 0 0 0; -v/E 1/E -v/E 0 0 0; -v/E -v/E 1/E 0 0 0; 0 0 0 2*(1+v)/E 0 0; 0 0 0 0 2*(1+v)/E 0; 0 0 0 0 0 2*(1+v)/E];
amatte = Gmat/10^6;
allcases = [30 20 25 10 15 0 0; 35 20 25 10 12 20 1e-5; 25 20 40 10 15 0 0];
for k = 1:size(allcases, 1)
    a = allcases(k, :);
    Pp = a(4); Gfp = a(5) - Pp; Gtc = a(6); Gec = a(7);
    SHmax = a(1)-Pp; Shmin = a(2)-Pp; Sv = a(3)-Pp; Pmud = Pp + Gfp;
    S_g = bsa_Sg(SHmax, Shmin, Sv);
    delta = 0: pi/20: 2*pi; phi = 0: pi/20: pi/2;
    UCS = zeros(length(delta), length(phi));
    for i = 1:length(delta), for j = 1:length(phi)
        UCS(i,j) = calUCS(delta(i), phi(j), Pp, Pmud, v, S_g, amatte, Gtc, Gec);
    end, end
    deltaobb = 0 : pi/12 : 2*pi; phiobb = 0 : pi/12 : pi/2;
    OBB = zeros(length(deltaobb), length(phiobb));
    for i = 1:length(deltaobb), for j = 1:length(phiobb)
        OBB(i,j) = calOBB(deltaobb(i), phiobb(j), Pp, Pmud, v, S_g, amatte, Gtc, Gec);
    end, end
    out.allori(k).inputs = a; out.allori(k).S_g = S_g; out.allori(k).UCS = UCS; out.allori(k).OBB = OBB;
    fprintf('allori %d: UCS %.4f .. %.4f\n', k, min(UCS(:)), max(UCS(:)));
end

f = fullfile(root, 'tests', 'reference', 'borehole_matlab.json');
fid = fopen(f, 'w'); fwrite(fid, jsonencode(out), 'char'); fclose(fid);
fprintf('wrote %s\n', f);

% =====================================================================
function S_g = bsa_Sg(SHmax, Shmin, Sv)
        X = [0, 1, 0];
        Y = [1, 0, 0];
        Z = [0, 0, -1];

        % angle from the geographic coordinate system, Y(East)->X(North) is positive
        d_SHmax = 0*pi/180; % angle from the Y(East) axis
        d_Shmin = pi/2; % angle from the X(North) axis, (d_SHmax - pi/2)
        %d_v is same with original Z axis

        % direction vector of stress field
        v_SHmax = [cos(d_SHmax), sin(d_SHmax), 0];
        v_Shmin = [cos(d_Shmin), sin(d_Shmin), 0];
        v_Sv = Z;

        S = sort([SHmax, Shmin, Sv],'descend');
        S_s = [S(1),0,0;0,S(2),0;0,0,S(3)];

        % define direction cosine
        if Sv == S(1) %normal
            dS1 = v_Sv;
            dS2 = v_SHmax;
            dS3 = v_Shmin;

            l1 = dot(dS1,X)/(norm(dS1)*norm(X)); l2 = dot(dS1,Y)/(norm(dS1)*norm(Y)); l3 = dot(dS1,Z)/(norm(dS1)*norm(Z));
            m1 = dot(dS2,X)/(norm(dS2)*norm(X)); m2 = dot(dS2,Y)/(norm(dS2)*norm(Y)); m3 = dot(dS2,Z)/(norm(dS2)*norm(Z));
            n1 = dot(dS3,X)/(norm(dS3)*norm(X)); n2 = dot(dS3,Y)/(norm(dS3)*norm(Y)); n3 = dot(dS3,Z)/(norm(dS3)*norm(Z));

        elseif Sv == S(2) %strike-slip
            dS1 = v_SHmax;
            dS2 = v_Sv;
            dS3 = v_Shmin;

            l1 = dot(dS1,X)/(norm(dS1)*norm(X)); l2 = dot(dS1,Y)/(norm(dS1)*norm(Y)); l3 = dot(dS1,Z)/(norm(dS1)*norm(Z));
            m1 = dot(dS2,X)/(norm(dS2)*norm(X)); m2 = dot(dS2,Y)/(norm(dS2)*norm(Y)); m3 = dot(dS2,Z)/(norm(dS2)*norm(Z));
            n1 = dot(dS3,X)/(norm(dS3)*norm(X)); n2 = dot(dS3,Y)/(norm(dS3)*norm(Y)); n3 = dot(dS3,Z)/(norm(dS3)*norm(Z));
        else
            dS1 = v_SHmax;
            dS2 = v_Shmin;
            dS3 = v_Sv;

            l1 = dot(dS1,X)/(norm(dS1)*norm(X)); l2 = dot(dS1,Y)/(norm(dS1)*norm(Y)); l3 = dot(dS1,Z)/(norm(dS1)*norm(Z));
            m1 = dot(dS2,X)/(norm(dS2)*norm(X)); m2 = dot(dS2,Y)/(norm(dS2)*norm(Y)); m3 = dot(dS2,Z)/(norm(dS2)*norm(Z));
            n1 = dot(dS3,X)/(norm(dS3)*norm(X)); n2 = dot(dS3,Y)/(norm(dS3)*norm(Y)); n3 = dot(dS3,Z)/(norm(dS3)*norm(Z));
        end

        R_s = [l1, l2, l3; m1, m2, m3; n1, n2, n3];
        S_g = R_s'*S_s*R_s;
end

function [Sr, St, Sz, Trt, Trz, Ttz, Sp1, Sp2, Sp3, dispxx, dispyy, gridr, gridtheta, mu, lbd] = ...
        bsa_analytic(Gmat, Sx, Sy, Sz_, Sxy, Syz, Sxz, Gpp, Pmud, Gtc, Gec, Gr, polardeg, azideg)
    amatte = Gmat/10^6;
    Gsxi=(Sx-Gpp)*10^6; Gsyi=(Sy-Gpp)*10^6; Gszi=(Sz_-Gpp)*10^6;
    Gsxyi=Sxy*10^6; Gsyzi=Syz*10^6; Gsxzi=Sxz*10^6;
    Gfp=0; if ~isnan(Pmud), Gfp=(Pmud-Gpp)*10^6; end
    Gpol=polardeg*2*pi/360; Gazi=azideg*2*pi/360;
        % Matrix Transform by Ong(1994)
        L1=cos(Gpol)*cos(Gazi);
        L2=-sin(Gazi);
        L3=sin(Gpol)*cos(Gazi);
        M1=cos(Gpol)*sin(Gazi);
        M2=cos(Gazi);
        M3=sin(Gazi)*sin(Gpol);
        N1=-sin(Gpol);
        N2=0;
        N3=cos(Gpol);

        Tsig=[L1^2 M1^2 N1^2 2*M1*N1 2*N1*L1 2*L1*M1;
            L2^2 M2^2 N2^2 2*M2*N2 2*N2*L2 2*L2*M2;
            L3^2 M3^2 N3^2 2*M3*N3 2*N3*L3 2*L3*M3;
            L2*L3 M2*M3 N2*N3 M2*N3+M3*N2 N2*L3+N3*L2 L2*M3+L3*M2;
            L3*L1 M3*M1 N3*N1 M1*N3+M3*N1 N1*L3+N3*L1 L1*M3+L3*M1;
            L1*L2 M1*M2 N1*N2 M1*N2+M2*N1 N1*L2+N2*L1 L1*M2+L2*M1];


        devst=Tsig*[Gsxi;Gsyi;Gszi;Gsxzi;Gsyzi;Gsxyi];  %시추공 좌표계로 변환된 응력값
        Gsx=devst(1);
        Gsy=devst(2);
        Gsz=devst(3);
        Gtyz=devst(4);
        Gtxz=devst(5);
        Gtxy=devst(6);

        amat=transpose(Tsig)*amatte*Tsig;
        if true

            bmat=zeros([6,6]); %reduced strain coefficient by Lekhnitskii
            for i=1:6
                for j=1:6
                    bmat(i,j)=amat(i,j)-(amat(i,3)*amat(j,3))/amat(3,3);
                end
            end
            % syms symmu
            % eqn = (bmat(1,1)*symmu^4-2*bmat(1,6)*symmu^3+(2*bmat(1,2)+bmat(6,6))*symmu^2 -2*bmat(2,6)*symmu+bmat(2,2))*(bmat(5,5)*symmu^2-2*bmat(4,5)*symmu+bmat(4,4))-(bmat(1,5)*symmu^3-(bmat(1,4)+bmat(5,6))*symmu^2+(bmat(2,5)+bmat(4,6))*symmu-bmat(2,4))^2 ==0;
            % solmu=solve(eqn, symmu);

            %Ong(1994), equation 3.3.4-3.3.5
            p = [ bmat(1,1)*bmat(5,5)-bmat(1,5)^2 ...
                2*bmat(1,5)*(bmat(1,4)+bmat(5,6))-2*bmat(1,1)*bmat(4,5)-2*bmat(1,6)*bmat(5,5) ...
                bmat(1,1)*bmat(4,4)+4*bmat(1,6)*bmat(4,5)+bmat(5,5)*(2*bmat(1,2)+bmat(6,6))-2*bmat(1,5)*(bmat(2,5)+bmat(4,6))-(bmat(1,4)+bmat(5,6))^2 ...
                2*bmat(1,5)*bmat(2,4)+2*(bmat(1,4)+bmat(5,6))*(bmat(2,5)+bmat(4,6))-2*bmat(1,6)*bmat(4,4)-2*bmat(4,5)*(2*bmat(1,2)+bmat(6,6))-2*bmat(2,6)*bmat(5,5) ...
                bmat(4,4)*(2*bmat(1,2)+bmat(6,6))+4*bmat(2,6)*bmat(4,5)+bmat(2,2)*bmat(5,5)-2*bmat(2,4)*(bmat(1,4)+bmat(5,6))-(bmat(2,5)+bmat(4,6))^2 ...
                2*bmat(2,4)*(bmat(2,5)+bmat(4,6))-2*bmat(2,6)*bmat(4,4)-2*bmat(2,2)*bmat(4,5) ...
                bmat(2,2)*bmat(4,4)-bmat(2,4)^2 ];
            solmu = roots(p);

            doublesolmu=double(solmu);
            solj=1;
            tempmu=zeros([1,6]);
            for solk=1:6
                if imag(doublesolmu(solk))>0
                    tempmu(solj)=doublesolmu(solk);
                    solj=solj+1;
                end
            end
            %근의 상호 중첩 방지
            mu(1)=1.0001*tempmu(1);
            mu(2)=1.0002*tempmu(2);
            mu(3)=1.0003*tempmu(3);
            sort(mu, 'descend');


            lbd(1)=-(bmat(1,5)*mu(1)^3-(bmat(1,4)+bmat(5,6))*mu(1)^2+(bmat(2,5)+bmat(4,6))*mu(1)-bmat(2,4))/(bmat(5,5)*mu(1)^2-2*bmat(4,5)*mu(1)+bmat(4,4));
            lbd(2)=-(bmat(1,5)*mu(2)^3-(bmat(1,4)+bmat(5,6))*mu(2)^2+(bmat(2,5)+bmat(4,6))*mu(2)-bmat(2,4))/(bmat(5,5)*mu(2)^2-2*bmat(4,5)*mu(2)+bmat(4,4));
            lbd(3)=-(bmat(1,5)*mu(3)^3-(bmat(1,4)+bmat(5,6))*mu(3)^2+(bmat(2,5)+bmat(4,6))*mu(3)-bmat(2,4))/(bmat(1,1)*mu(3)^4-2*bmat(1,6)*mu(3)^3+(2*bmat(1,2)+bmat(6,6))*mu(3)^2 -2*bmat(2,6)*mu(3)+bmat(2,2));



            %   r=Gr:0.001:10*Gr;
            r=(1:0.05:10)*Gr;
            r=r';
            theta=0: 1/360 *pi/2 : 2*pi;
            theta=theta';
            R=Gr;
            Del=mu(2)-mu(1)+lbd(3)*lbd(2)*(mu(1)-mu(3)) +lbd(1)*lbd(3)*(mu(3)-mu(2));
            p1=bmat(1,1)*mu(1)^2 +bmat(1,2)-bmat(1,6)*mu(1)+lbd(1)*(bmat(1,5)*mu(1)-bmat(1,4));
            p2=bmat(1,1)*mu(2)^2+bmat(1,2)-bmat(1,6)*mu(2)+lbd(2)*(bmat(1,5)*mu(2)-bmat(1,4));
            p3=lbd(3)*(bmat(1,1)*mu(3)^2+bmat(1,2)-bmat(1,6)*mu(3))+bmat(1,5)*mu(3)-bmat(1,4);
            q1=bmat(1,2)*mu(1)+bmat(2,2)/mu(1)-bmat(2,6)+lbd(1)*(bmat(2,5)-bmat(2,4)/mu(1));
            q2=bmat(1,2)*mu(2)+bmat(2,2)/mu(2)-bmat(2,6)+lbd(2)*(bmat(2,5)-bmat(2,4)/mu(2));
            q3=lbd(3)*(bmat(1,2)*mu(3)+bmat(2,2)/mu(3) -bmat(2,6))+bmat(2,5)-bmat(2,4)/mu(3);

            z1=zeros([length(r),length(theta)]);
            z2=zeros([length(r),length(theta)]);
            z3=zeros([length(r),length(theta)]);
            deter1=zeros([length(r),length(theta)]);
            deter2=zeros([length(r),length(theta)]);
            deter3=zeros([length(r),length(theta)]);
            detert1=zeros([length(r),length(theta)]);
            detert2=zeros([length(r),length(theta)]);
            detert3=zeros([length(r),length(theta)]);
            zeta1=zeros([length(r),length(theta)]);
            zeta2=zeros([length(r),length(theta)]);
            zeta3=zeros([length(r),length(theta)]);
            Phi1=zeros([length(r),length(theta)]);
            Phi2=zeros([length(r),length(theta)]);
            Phi3=zeros([length(r),length(theta)]);
            Txy=zeros([length(r),length(theta)]);
            Txz=zeros([length(r),length(theta)]);
            Tyz=zeros([length(r),length(theta)]);
            Sxx=zeros([length(r),length(theta)]);
            Syy=zeros([length(r),length(theta)]);
            Szz=zeros([length(r),length(theta)]);
            pphi1=zeros([length(r),length(theta)]);
            pphi2=zeros([length(r),length(theta)]);
            pphi3=zeros([length(r),length(theta)]);
            dispxx=zeros([length(r),length(theta)]);
            dispyy=zeros([length(r),length(theta)]);
            epxx=zeros([length(r),length(theta)]);
            epyy=zeros([length(r),length(theta)]);
            Sr=zeros([length(r),length(theta)]);
            St=zeros([length(r),length(theta)]);
            Sz=zeros([length(r),length(theta)]);
            Trt=zeros([length(r),length(theta)]);
            Trz=zeros([length(r),length(theta)]);
            Ttz=zeros([length(r),length(theta)]);
            Sp1=zeros([length(r),length(theta)]);
            Sp2=zeros([length(r),length(theta)]);
            Sp3=zeros([length(r),length(theta)]);
            thermalst = zeros([length(r),length(theta)]);

            %Following Ong(1994), 3.4
            for countr=1:length(r)
                stsign1=1;
                stsign2=1;
                stsign3=1;
                detsign1=1;
                detsign2=1;
                detsign3=1;
                for countth=1:length(theta)
                    z1(countr,countth)=r(countr)*(cos(theta(countth)) + mu(1)*sin(theta(countth)));
                    z2(countr,countth)=r(countr)*(cos(theta(countth)) + mu(2)*sin(theta(countth)));
                    z3(countr,countth)=r(countr)*(cos(theta(countth)) + mu(3)*sin(theta(countth)));
                    deter1(countr,countth)=(z1(countr,countth)/R)^2 -1 -mu(1)^2;
                    deter2(countr,countth)=(z2(countr,countth)/R)^2 -1 -mu(2)^2;
                    deter3(countr,countth)=(z3(countr,countth)/R)^2 -1 -mu(3)^2;
                    if stsign1==1
                        if imag(deter1(countr,countth))>0
                            stsign1=-1;
                        end
                    end
                    if stsign1==-1
                        if imag(deter1(countr,countth))<0
                            stsign1=+1;
                            detsign1=-detsign1;
                        end
                    end
                    if stsign2==1
                        if imag(deter2(countr,countth))>0
                            stsign2=-1;
                        end
                    end
                    if stsign2==-1
                        if imag(deter2(countr,countth))<0
                            stsign2=+1;
                            detsign2=-detsign2;
                        end
                    end
                    if stsign3==1
                        if imag(deter3(countr,countth))>0
                            stsign3=-1;
                        end
                    end
                    if stsign3==-1
                        if imag(deter3(countr,countth))<0
                            stsign3=+1;
                            detsign3=-detsign3;
                        end
                    end
                    detert1(countr,countth)=detsign1*sqrt((z1(countr,countth)/R)^2 -1 -mu(1)^2);
                    detert2(countr,countth)=detsign2*sqrt((z2(countr,countth)/R)^2 -1 -mu(2)^2);
                    detert3(countr,countth)=detsign3*sqrt((z3(countr,countth)/R)^2 -1 -mu(3)^2);
                    zeta1(countr,countth)=(z1(countr,countth)/R + detert1(countr,countth))/(1-1i*mu(1)); %Ong(1994), eq 3.4.7
                    zeta2(countr,countth)=(z2(countr,countth)/R + detert2(countr,countth))/(1-1i*mu(2));
                    zeta3(countr,countth)=(z3(countr,countth)/R + detert3(countr,countth))/(1-1i*mu(3));
                    Phi1(countr,countth)=-(1/(2*Del*zeta1(countr,countth)*detert1(countr,countth)))    *((1i*Gtxy - Gsy+Gfp)*(mu(2)-lbd(2)*lbd(3)*mu(3))+(Gtxy-1i*Gsx+1i*Gfp)*(lbd(2)*lbd(3)-1)+(Gtyz-1i*Gtxz)*lbd(3)*(mu(3)-mu(2))); %Ong(1994), eq 3.4.11
                    Phi2(countr,countth)=-(1/(2*Del*zeta2(countr,countth)*detert2(countr,countth)))    *((1i*Gtxy - Gsy+Gfp)*(lbd(1)*lbd(3)*mu(3)-mu(1))+(Gtxy-1i*Gsx+1i*Gfp)*(1-lbd(1)*lbd(3))+(Gtyz-1i*Gtxz)*lbd(3)*(mu(1)-mu(3)));
                    Phi3(countr,countth)=-(1/(2*Del*zeta3(countr,countth)*detert3(countr,countth)))    *((1i*Gtxy - Gsy+Gfp)*(mu(1)*lbd(2)-mu(2)*lbd(1))+(Gtxy-1i*Gsx+1i*Gfp)*(lbd(1)-lbd(2))+(Gtyz-1i*Gtxz)*(mu(2)-mu(1)));
                    Sxx(countr,countth)=Gsx+2*real(mu(1)^2*Phi1(countr,countth)+mu(2)^2*Phi2(countr,countth)+(lbd(3)*mu(3)^2)*Phi3(countr,countth)); %Ong(1994), eq 3.3.20
                    Syy(countr,countth)=Gsy+2*real(Phi1(countr,countth)+Phi2(countr,countth)+lbd(3)*Phi3(countr,countth));
                    Txy(countr,countth)=Gtxy-2*real(mu(1)*Phi1(countr,countth)+mu(2)*Phi2(countr,countth)+(lbd(3)*mu(3)*Phi3(countr,countth)));
                    Txz(countr,countth)=Gtxz+2*real(mu(1)*lbd(1)*Phi1(countr,countth)+mu(2)*lbd(2)*Phi2(countr,countth)+mu(3)*Phi3(countr,countth));
                    Tyz(countr,countth)=Gtyz-2*real(lbd(1)*Phi1(countr,countth)+lbd(2)*Phi2(countr,countth)+Phi3(countr,countth));
                    Szz(countr,countth)=Gsz-(1/amat(3,3))*(amat(3,1)*(Sxx(countr,countth)-Gsx)+amat(3,2)*(Syy(countr,countth)-Gsy)+amat(3,4)*(Tyz(countr,countth)-Gtyz)+amat(3,5)*(Txz(countr,countth)-Gtxz)+amat(3,6)*(Txy(countr,countth)-Gtxy));
                    pphi1(countr,countth)=R/(2*Del*zeta1(countr,countth)) *((1i*Gtxy - Gsy+Gfp)*(mu(2)-lbd(2)*lbd(3)*mu(3))+(Gtxy-1i*Gsx+1i*Gfp)*(lbd(2)*lbd(3)-1)+(Gtyz-1i*Gsz)*lbd(3)*(mu(3)-mu(2)));
                    pphi2(countr,countth)=R/(2*Del*zeta2(countr,countth)) *((1i*Gtxy - Gsy+Gfp)*(lbd(1)*lbd(3)*mu(3)-mu(1))+(Gtxy-1i*Gsx+1i*Gfp)*(1-lbd(1)*lbd(3))+(Gtyz-1i*Gsz)*lbd(3)*(mu(1)-mu(3)));
                    pphi3(countr,countth)=R/(2*Del*zeta3(countr,countth)) *((1i*Gtxy - Gsy+Gfp)*(mu(1)*lbd(2)-mu(2)*lbd(1))+(Gtxy-1i*Gsx+1i*Gfp)*(lbd(1)-lbd(2))+(Gtyz-1i*Gsz)*(mu(2)-mu(1)));
                    dispxx(countr,countth)=2*real(p1*pphi1(countr,countth)+p2*pphi2(countr,countth)+p3*pphi3(countr,countth));
                    dispyy(countr,countth)=2*real(q1*pphi1(countr,countth)+q2*pphi2(countr,countth)+q3*pphi3(countr,countth));
                end
            end

            % Thermal expansion
            ep=zeros(1,6);
            eptemp=zeros(6,6);

            for countr=1:length(r)
                for countth=1:length(theta)
                    L11=cos(theta(countth));
                    L22=-sin(theta(countth));
                    L33=0;
                    M11=sin(theta(countth));
                    M22=cos(theta(countth));
                    M33=0;
                    N11=0;
                    N22=0;
                    N33=1;

                    eptrans=[L11^2 M11^2 N11^2 2*M11*N11 2*N11*L11 2*L11*M11;
                        L22^2 M22^2 N22^2 2*M22*N22 2*N22*L22 2*L22*M22;
                        L33^2 M33^2 N33^2 2*M33*N33 2*N33*L33 2*L33*M33;
                        L22*L33 M22*M33 N22*N33 M22*N33+M33*N22 N22*L33+N33*L22 L22*M33+L33*M22;
                        L33*L11 M33*M11 N33*N11 M11*N33+M33*N11 N11*L33+N33*L11 L11*M33+L33*M11;
                        L11*L22 M11*M22 N11*N22 M11*N22+M22*N11 N11*L22+N22*L11 L11*M22+L22*M11];

                    epthertemp=transpose(eptrans)*amat*eptrans;
                    epther=epthertemp(2:3,2:3);
                    stthertemp=mldivide(epther,[Gtc*Gec;Gtc*Gec]);
                    thermalst(countr,countth)=stthertemp(1);
                    stther=mldivide(eptrans,[0;stthertemp(1);stthertemp(2);0;0;0]);

                    Sxx(countr,countth)=Sxx(countr,countth)+stther(1);
                    Syy(countr,countth)=Syy(countr,countth)+stther(2);
                    Szz(countr,countth)=Szz(countr,countth)+stther(3);
                    Tyz(countr,countth)=Tyz(countr,countth)+stther(4);
                    Txz(countr,countth)=Txz(countr,countth)+stther(5);
                    Txy(countr,countth)=Txy(countr,countth)+stther(6);
                end
            end


            for countr=1:length(r)
                for countth=1:length(theta)
                    temp=[cos(theta(countth)) sin(theta(countth)) 0;
                        -sin(theta(countth)) cos(theta(countth)) 0;
                        0 0 1]*[Sxx(countr,countth) Txy(countr,countth) Txz(countr,countth);
                        Txy(countr,countth) Syy(countr,countth) Tyz(countr,countth);
                        Txz(countr,countth) Tyz(countr,countth) Szz(countr,countth)]*[cos(theta(countth)) -sin(theta(countth)) 0;
                        sin(theta(countth)) cos(theta(countth)) 0;
                        0 0 1];
                    Sr(countr,countth)=temp(1,1);
                    St(countr,countth)=temp(2,2);
                    Sz(countr,countth)=temp(3,3);
                    Trt(countr,countth)=temp(1,2);
                    Trz(countr,countth)=temp(1,3);
                    Ttz(countr,countth)=temp(2,3);
                end
            end

            for i=1:length(Sr(:,1))
                for j=1:length(Sr(1,:))
                    Aeig=eig([Sr(i,j) Trt(i,j) Trz(i,j);
                        Trt(i,j) St(i,j) Ttz(i,j);
                        Trz(i,j) Ttz(i,j) Sz(i,j)]);
                    Beig = sort(Aeig);
                    Sp1(i,j) = Beig(3); %Max
                    Sp2(i,j) = Beig(2); %Mid
                    Sp3(i,j) = Beig(1); %Min
                end
            end
            [gridtheta, gridr]=meshgrid(theta,r);
            nodetheta=gridtheta;
            noder=gridr;
        end
end

function [srrele, sttele, srtele, xele, yele] = bsa_fem(Gmat, Sx, Sy, Sz_, Sxy, Syz, Sxz, Gpp, Pmud, Gtc, Gec, Gr, polardeg, azideg, rmesh, thmesh)
    amatte = Gmat/10^6;
    Gsxi=(Sx-Gpp)*10^6; Gsyi=(Sy-Gpp)*10^6; Gszi=(Sz_-Gpp)*10^6;
    Gsxyi=Sxy*10^6; Gsyzi=Syz*10^6; Gsxzi=Sxz*10^6;
    Gfp=0; if ~isnan(Pmud), Gfp=(Pmud-Gpp)*10^6; end
    Gpol=polardeg*2*pi/360; Gazi=azideg*2*pi/360;
        L1=cos(Gpol)*cos(Gazi);
        L2=-sin(Gazi);
        L3=sin(Gpol)*cos(Gazi);
        M1=cos(Gpol)*sin(Gazi);
        M2=cos(Gazi);
        M3=sin(Gazi)*sin(Gpol);
        N1=-sin(Gpol);
        N2=0;
        N3=cos(Gpol);

        Tsig=[L1^2 M1^2 N1^2 2*M1*N1 2*N1*L1 2*L1*M1;
            L2^2 M2^2 N2^2 2*M2*N2 2*N2*L2 2*L2*M2;
            L3^2 M3^2 N3^2 2*M3*N3 2*N3*L3 2*L3*M3;
            L2*L3 M2*M3 N2*N3 M2*N3+M3*N2 N2*L3+N3*L2 L2*M3+L3*M2;
            L3*L1 M3*M1 N3*N1 M1*N3+M3*N1 N1*L3+N3*L1 L1*M3+L3*M1;
            L1*L2 M1*M2 N1*N2 M1*N2+M2*N1 N1*L2+N2*L1 L1*M2+L2*M1];


        devst=Tsig*[Gsxi;Gsyi;Gszi;Gsxzi;Gsyzi;Gsxyi];  %시추공 좌표계로 변환된 응력값
        Gsx=devst(1);
        Gsy=devst(2);
        Gsz=devst(3);
        Gtyz=devst(4);
        Gtxz=devst(5);
        Gtxy=devst(6);

        amat=transpose(Tsig)*amatte*Tsig;
            rend=8*Gr;
            rghpo=floor(2*rmesh/3);           %rougher point
            rghco=10;                        %rougher coefficient
            nodep=zeros([(rmesh+1)*thmesh,2]);
            nodet=zeros([rmesh*thmesh, 4]);
            for thc=0:(thmesh/4 -1)
                r0x=Gr*cos(thc*2*pi/thmesh +pi/4);
                r0y=Gr*sin(thc*2*pi/thmesh +pi/4);
                rex=rend-thc*rend/(thmesh/8);
                rey=rend;
                for rc=0:rghpo
                    nodep(1+rc+(1+rmesh)*thc,:)=[r0x+(rex-r0x)*rc/rghco/rmesh,r0y+(rey-r0y)*rc/rghco/rmesh];
                end
                rghlox=r0x+(rex-r0x)*rghpo/rghco/rmesh;
                rghloy=r0y+(rey-r0y)*rghpo/rghco/rmesh;
                for rc=rghpo+1:rmesh
                    nodep(1+rc+(1+rmesh)*thc,:)=[rghlox+(rex-rghlox)*(rc-rghpo)/(rmesh-rghpo),rghloy+(rey-rghloy)*(rc-rghpo)/(rmesh-rghpo)];
                end
            end
            for thc=(thmesh/4):(thmesh/2 -1)
                r0x=Gr*cos(thc*2*pi/thmesh +pi/4);
                r0y=Gr*sin(thc*2*pi/thmesh +pi/4);
                rex=-rend;
                rey=rend-(thc-thmesh/4)*rend/(thmesh/8);
                for rc=0:rghpo
                    nodep(1+rc+(1+rmesh)*thc,:)=[r0x+(rex-r0x)*rc/rghco/rmesh,r0y+(rey-r0y)*rc/rghco/rmesh];
                end
                rghlox=r0x+(rex-r0x)*rghpo/rghco/rmesh;
                rghloy=r0y+(rey-r0y)*rghpo/rghco/rmesh;
                for rc=rghpo+1:rmesh
                    nodep(1+rc+(1+rmesh)*thc,:)=[rghlox+(rex-rghlox)*(rc-rghpo)/(rmesh-rghpo),rghloy+(rey-rghloy)*(rc-rghpo)/(rmesh-rghpo)];
                end
            end
            for thc=(thmesh/2):(thmesh*3/4 -1)
                r0x=Gr*cos(thc*2*pi/thmesh +pi/4);
                r0y=Gr*sin(thc*2*pi/thmesh +pi/4);
                rex=-rend+(thc-thmesh/2)*rend/(thmesh/8);
                rey=-rend;
                for rc=0:rghpo
                    nodep(1+rc+(1+rmesh)*thc,:)=[r0x+(rex-r0x)*rc/rghco/rmesh,r0y+(rey-r0y)*rc/rghco/rmesh];
                end
                rghlox=r0x+(rex-r0x)*rghpo/rghco/rmesh;
                rghloy=r0y+(rey-r0y)*rghpo/rghco/rmesh;
                for rc=rghpo+1:rmesh
                    nodep(1+rc+(1+rmesh)*thc,:)=[rghlox+(rex-rghlox)*(rc-rghpo)/(rmesh-rghpo),rghloy+(rey-rghloy)*(rc-rghpo)/(rmesh-rghpo)];
                end
            end
            for thc=(thmesh*3/4):(thmesh-1)
                r0x=Gr*cos(thc*2*pi/thmesh +pi/4);
                r0y=Gr*sin(thc*2*pi/thmesh +pi/4);
                rex=rend;
                rey=-rend+(thc-thmesh*3/4)*rend/(thmesh/8);
                for rc=0:rghpo
                    nodep(1+rc+(1+rmesh)*thc,:)=[r0x+(rex-r0x)*rc/rghco/rmesh,r0y+(rey-r0y)*rc/rghco/rmesh];
                end
                rghlox=r0x+(rex-r0x)*rghpo/rghco/rmesh;
                rghloy=r0y+(rey-r0y)*rghpo/rghco/rmesh;
                for rc=rghpo+1:rmesh
                    nodep(1+rc+(1+rmesh)*thc,:)=[rghlox+(rex-rghlox)*(rc-rghpo)/(rmesh-rghpo),rghloy+(rey-rghloy)*(rc-rghpo)/(rmesh-rghpo)];
                end
            end
            for thc=0:thmesh-2
                for rc=1:rmesh
                    nodet(rc-1+thc*rmesh+1,:)=[rc+thc*(rmesh+1),rc+thc*(rmesh+1)+1,rc+(thc+1)*(rmesh+1)+1,rc+(thc+1)*(rmesh+1)];
                end
            end
            thc=thmesh-1;
            for rc=1:rmesh
                nodet(rc-1+thc*rmesh+1,:)=[rc+thc*(rmesh+1),rc+thc*(rmesh+1)+1,rc+(0)*(rmesh+1)+1,rc+(0)*(rmesh+1)];
            end

            % Material properties


            inva=inv(amat);
            invC=[amat(1,1) amat(2,1) amat(6,1); amat(2,1) amat(2,2) amat(2,6); amat(6,1) amat(6,2) amat(6,6)];
            C=inv(invC);
            %% Setting system equation

            % Default K and F matrix
            Ktot=zeros(2*size(nodep,1));
            Ftot=zeros(2*size(nodep,1),1);

            for kcount=1:size(nodet,1)       % repeat for every element
                % Numbering each node
                no1=nodet(kcount,1);
                no2=nodet(kcount,2);
                no3=nodet(kcount,3);
                no4=nodet(kcount,4);

                %coordinate of each node
                x1=nodep(no1,1);
                x2=nodep(no2,1);
                x3=nodep(no3,1);
                x4=nodep(no4,1);
                y1=nodep(no1,2);
                y2=nodep(no2,2);
                y3=nodep(no3,2);
                y4=nodep(no4,2);

                %             gp=[-1/sqrt(3),1/sqrt(3)];      %Gauss point for Gauss-Legandre quadrature rules
                gp=[-sqrt(3/5), 0, sqrt(3/5)];
                gpwt=[25/81, 40/81, 25/81; 40/81, 64/81, 40/81; 25/81, 40/81, 25/81];
                for gpx=1:length(gp)
                    for gpy=1:length(gp)
                        gpzeta=gp(gpx);
                        gpeta=gp(gpy);
                        gpjacob=(1/4) * [(x2-x1)*(1-gpeta)+(x3-x4)*(1+gpeta) (y2-y1)*(1-gpeta)+(y3-y4)*(1+gpeta);
                            (x4-x1)*(1-gpzeta)+(x3-x2)*(1+gpzeta) (y4-y1)*(1-gpzeta)+(y3-y2)*(1+gpzeta)];

                        bmat=(1/4/abs(det(gpjacob))) * [-(1-gpeta)*gpjacob(2,2)+(1-gpzeta)*gpjacob(1,2),0,(1-gpeta)*gpjacob(2,2)+(1+gpzeta)*gpjacob(1,2),0,(1+gpeta)*gpjacob(2,2)-(1+gpzeta)*gpjacob(1,2),0,-(1+gpeta)*gpjacob(2,2)-(1-gpzeta)*gpjacob(1,2),0;
                            0,(1-gpeta)*gpjacob(2,1)-(1-gpzeta)*gpjacob(1,1),0,-(1-gpeta)*gpjacob(2,1)-(1+gpzeta)*gpjacob(1,1),0,-(1+gpeta)*gpjacob(2,1)+(1+gpzeta)*gpjacob(1,1),0,(1+gpeta)*gpjacob(2,1)+(1-gpzeta)*gpjacob(1,1);
                            (1-gpeta)*gpjacob(2,1)-(1-gpzeta)*gpjacob(1,1),-(1-gpeta)*gpjacob(2,2)+(1-gpzeta)*gpjacob(1,2),-(1-gpeta)*gpjacob(2,1)-(1+gpzeta)*gpjacob(1,1),(1-gpeta)*gpjacob(2,2)+(1+gpzeta)*gpjacob(1,2),-(1+gpeta)*gpjacob(2,1)+(1+gpzeta)*gpjacob(1,1),(1+gpeta)*gpjacob(2,2)-(1+gpzeta)*gpjacob(1,2),(1+gpeta)*gpjacob(2,1)+(1-gpzeta)*gpjacob(1,1),-(1+gpeta)*gpjacob(2,2)-(1-gpzeta)*gpjacob(1,2)];


                        K=gpwt(gpx,gpy)*bmat'*C*bmat*abs(det(gpjacob));



                        nomat=[no1,no2,no3,no4];
                        for nomatnum2=1:4
                            for nomatnum1=1:4
                                Ktot(nomat(nomatnum1)*2-1,nomat(nomatnum2)*2-1)=Ktot(nomat(nomatnum1)*2-1,nomat(nomatnum2)*2-1)+K(2*nomatnum1-1,2*nomatnum2-1);
                                Ktot(nomat(nomatnum1)*2,nomat(nomatnum2)*2-1)=Ktot(nomat(nomatnum1)*2,nomat(nomatnum2)*2-1)+K(2*nomatnum1,2*nomatnum2-1);
                                Ktot(nomat(nomatnum1)*2-1,nomat(nomatnum2)*2)=Ktot(nomat(nomatnum1)*2-1,nomat(nomatnum2)*2)+K(2*nomatnum1-1,2*nomatnum2);
                                Ktot(nomat(nomatnum1)*2,nomat(nomatnum2)*2)=Ktot(nomat(nomatnum1)*2,nomat(nomatnum2)*2)+K(2*nomatnum1,2*nomatnum2);
                            end
                        end
                    end
                end

            end




            %% Boundary Condtion
            kcount=rmesh+1;
            Ftot(2*kcount,1)=Ftot(2*kcount,1)+ rend/(thmesh/4)* (Gsy+Gtxy);
            Ftot(2*kcount-1,1)=Ftot(2*kcount,1)+ rend/(thmesh/4)* (Gsx+Gtxy);
            for kcount=2*rmesh+2:rmesh+1:length(nodep)/4
                Ftot(2*kcount,1)=Ftot(2*kcount,1)+ rend*2/(thmesh/4)* Gsy;
                Ftot(2*kcount-1,1)=Ftot(2*kcount-1,1)+ rend*2/(thmesh/4)*Gtxy;
            end
            kcount=length(nodep)/4 +rmesh+1;
            Ftot(2*kcount,1)=Ftot(2*kcount,1)+ rend/(thmesh/4)* (Gsy+Gtxy);
            Ftot(2*kcount-1,1)=Ftot(2*kcount-1,1)- rend/(thmesh/4)* (Gsx+Gtxy);

            for kcount=length(nodep)/4 +2*rmesh+2:rmesh+1:length(nodep)/2
                Ftot(2*kcount,1)=Ftot(2*kcount,1)- rend*2/(thmesh/4)* Gtxy;
                Ftot(2*kcount-1,1)=Ftot(2*kcount-1,1)- rend*2/(thmesh/4)* Gsx;
            end
            kcount=length(nodep)/2+rmesh+1;
            Ftot(2*kcount,1)=Ftot(2*kcount,1)- rend/(thmesh/4)* (Gsy+Gtxy);
            Ftot(2*kcount-1,1)=Ftot(2*kcount-1,1)- rend/(thmesh/4)* (Gsx+Gtxy);
            for kcount=length(nodep)/2+2*rmesh+2:rmesh+1:length(nodep)*3/4
                Ftot(2*kcount,1)=Ftot(2*kcount,1)- rend*2/(thmesh/4)* Gsy;
                Ftot(2*kcount-1,1)=Ftot(2*kcount-1,1)- rend*2/(thmesh/4)* Gtxy;
            end
            kcount=length(nodep)*3/4 +rmesh+1;
            Ftot(2*kcount,1)=Ftot(2*kcount,1)- rend/(thmesh/4)* (Gsy+Gtxy);
            Ftot(2*kcount-1,1)=Ftot(2*kcount-1,1)+ rend/(thmesh/4)* (Gsx+Gtxy);
            for kcount=length(nodep)*3/4+2*rmesh+2:rmesh+1:length(nodep)
                Ftot(2*kcount,1)=Ftot(2*kcount,1)+ rend*2/(thmesh/4)* Gtxy;
                Ftot(2*kcount-1,1)=Ftot(2*kcount-1,1)+ rend*2/(thmesh/4)* Gsx;
            end
            %Fluid pressure
            for kcount=1:rmesh+1:length(nodep)

                Ftot(2*kcount-1)=Ftot(2*kcount-1)-Gfp*nodep(kcount,1)*2*pi/thmesh;
                Ftot(2*kcount)=Ftot(2*kcount)-Gfp*nodep(kcount,2)*2*pi/thmesh;
            end

            atot=pinv(Ktot)*Ftot; %


            %% Evaluating Flux

            strainele=zeros([size(nodet,1),3]);
            stressele=zeros([size(nodet,1),3]);
            xele=zeros([size(nodet,1),1]);
            yele=zeros([size(nodet,1),1]);
            srrele=zeros([size(nodet,1),1]);
            sttele=zeros([size(nodet,1),1]);
            srtele=zeros([size(nodet,1),1]);
            sxxele=zeros([size(nodet,1),1]);
            syyele=zeros([size(nodet,1),1]);
            sxyele=zeros([size(nodet,1),1]);
            thermalstele=zeros([size(nodet,1),1]);
            for kcount=1:size(nodet,1)

                no1=nodet(kcount,1);
                no2=nodet(kcount,2);
                no3=nodet(kcount,3);
                no4=nodet(kcount,4);
                x1=nodep(no1,1);
                x2=nodep(no2,1);
                x3=nodep(no3,1);
                x4=nodep(no4,1);
                y1=nodep(no1,2);
                y2=nodep(no2,2);
                y3=nodep(no3,2);
                y4=nodep(no4,2);
                gpeta=0;
                gpzeta=0;
                gpjacob=1/4 * [(x2-x1)*(1-gpeta)+(x3-x4)*(1+gpeta) (y2-y1)*(1-gpeta)+(y3-y4)*(1+gpeta);
                    (x4-x1)*(1-gpzeta)+(x3-x2)*(1+gpzeta) (y4-y1)*(1-gpzeta)+(y3-y2)*(1+gpzeta)];
                bmat=(1/4/abs(det(gpjacob))) * [-(1-gpeta)*gpjacob(2,2)+(1-gpzeta)*gpjacob(1,2),0,(1-gpeta)*gpjacob(2,2)+(1+gpzeta)*gpjacob(1,2),0,(1+gpeta)*gpjacob(2,2)-(1+gpzeta)*gpjacob(1,2),0,-(1+gpeta)*gpjacob(2,2)-(1-gpzeta)*gpjacob(1,2),0;
                    0,(1-gpeta)*gpjacob(2,1)-(1-gpzeta)*gpjacob(1,1),0,-(1-gpeta)*gpjacob(2,1)-(1+gpzeta)*gpjacob(1,1),0,-(1+gpeta)*gpjacob(2,1)+(1+gpzeta)*gpjacob(1,1),0,(1+gpeta)*gpjacob(2,1)+(1-gpzeta)*gpjacob(1,1);
                    (1-gpeta)*gpjacob(2,1)-(1-gpzeta)*gpjacob(1,1),-(1-gpeta)*gpjacob(2,2)+(1-gpzeta)*gpjacob(1,2),-(1-gpeta)*gpjacob(2,1)-(1+gpzeta)*gpjacob(1,1),(1-gpeta)*gpjacob(2,2)+(1+gpzeta)*gpjacob(1,2),-(1+gpeta)*gpjacob(2,1)+(1+gpzeta)*gpjacob(1,1),(1+gpeta)*gpjacob(2,2)-(1+gpzeta)*gpjacob(1,2),(1+gpeta)*gpjacob(2,1)+(1-gpzeta)*gpjacob(1,1),-(1+gpeta)*gpjacob(2,2)-(1-gpzeta)*gpjacob(1,2)];


                % Calculation of a matrix for this node (displacement)
                aele(1,1)=atot(2*no1-1,1);
                aele(2,1)=atot(2*no1,1);
                aele(3,1)=atot(2*no2-1,1);
                aele(4,1)=atot(2*no2,1);
                aele(5,1)=atot(2*no3-1,1);
                aele(6,1)=atot(2*no3,1);
                aele(7,1)=atot(2*no4-1,1);
                aele(8,1)=atot(2*no4,1);



                strainele(kcount,:)=(bmat*aele)';           % total strain matrix for each element, (x, y, xy)
                stressele(kcount,:)=(C*bmat*aele)';         % total stress matrix for each element, (x, y, xy)
                xele(kcount)=(x1+x2+x3+x4)/4;
                yele(kcount)=(y1+y2+y3+y4)/4;               % coordinate of each element
                [thele,rele]=cart2pol(xele,yele);   % polar coordinate of each element

                % calculation of polar coordinate stress distribution
                srrele(kcount)=stressele(kcount,1) * (cos(thele(kcount)))^2 +2*stressele(kcount,3)*(sin(thele(kcount)) *cos(thele(kcount)))+stressele(kcount,2) *(sin(thele(kcount)))^2;
                sttele(kcount)=stressele(kcount,1) * (sin(thele(kcount)))^2 -2*stressele(kcount,3)*(sin(thele(kcount)) *cos(thele(kcount)))+stressele(kcount,2) *(cos(thele(kcount)))^2;
                srtele(kcount)=(stressele(kcount,2)-stressele(kcount,1))*sin(thele(kcount))*cos(thele(kcount)) +stressele(kcount,3)*((cos(thele(kcount)))^2 -(sin(thele(kcount)))^2);

                %         Thermal stress
                ep=zeros(1,6);
                eptemp=zeros(6,6);

                L11=cos(thele(kcount));
                L22=-sin(thele(kcount));
                L33=0;
                M11=sin(thele(kcount));
                M22=cos(thele(kcount));
                M33=0;
                N11=0;
                N22=0;
                N33=1;

                eptrans=[L11^2 M11^2 N11^2 2*M11*N11 2*N11*L11 2*L11*M11; L22^2 M22^2 N22^2 2*M22*N22 2*N22*L22 2*L22*M22; L33^2 M33^2 N33^2 2*M33*N33 2*N33*L33 2*L33*M33; L22*L33 M22*M33 N22*N33 M22*N33+M33*N22 N22*L33+N33*L22 L22*M33+L33*M22; L33*L11 M33*M11 N33*N11 M11*N33+M33*N11 N11*L33+N33*L11 L11*M33+L33*M11; L11*L22 M11*M22 N11*N22 M11*N22+M22*N11 N11*L22+N22*L11 L11*M22+L22*M11];

                epthertemp=transpose(eptrans)*amat*eptrans;
                epther=epthertemp(2:3,2:3);
                stthertemp=epther\[Gtc*Gec;Gtc*Gec];
                thermalstele(kcount)=stthertemp(1);
                sttele(kcount)=sttele(kcount)+thermalstele(kcount);
                stther=eptrans\[0;stthertemp(1);stthertemp(2);0;0;0];

                sxxele(kcount)=stther(1);
                syyele(kcount)=stther(2);
                sxyele(kcount)=stther(6);
            end

            % Stress distribution
            sxxele=sxxele+stressele(:,1);
            syyele=syyele+stressele(:,2);
            sxyele=sxyele+stressele(:,3);
end

function [rbbo, thetabbo] = bsa_bbo(Gucs, Gfri, thetaop, rop, Sp1op, Sp3op)
            Smc(1,1:length(thetaop(1,:)))=Gucs+Sp3op(1,1:length(thetaop(1,:)))*(1+sin(Gfri))/(1-sin(Gfri))-Sp1op(1,1:length(thetaop(1,:)));
            rbbo=0;
            thetabbo=0;
            [minSmc, i_theta_minSmc] = min(Smc(1,:));
            %[min.Smc on the borehole wall, theta index of min.Smc]
            if minSmc<=0 % meets M-C criterion on some point of the borehole wall
                if max(Smc)<=0 % M-C failure in all around the borehole wall
                    thetabbo=pi;
                    for i_theta = i_theta_minSmc-359:i_theta_minSmc+359
                        i_r = 1;
                        while Gucs+Sp3op(i_r,i_theta)*(1+sin(Gfri))/(1-sin(Gfri))-Sp1op(i_r,i_theta)<=0
                            i_r=i_r+1;
                        end
                        if rop(i_r-1,1)>rbbo
                            rbbo=rop(i_r-1,1);
                        end
                    end
                else % typical borehole breakout
                    i_theta=i_theta_minSmc;
                    while Gucs+Sp3op(1,i_theta)*(1+sin(Gfri))/(1-sin(Gfri))-Sp1op(1,i_theta)<=0
                        i_theta=i_theta-1;
                    end
                    i_theta1=i_theta+1;
                    i_theta=i_theta_minSmc;
                    while Gucs+Sp3op(1,i_theta)*(1+sin(Gfri))/(1-sin(Gfri))-Sp1op(1,i_theta)<=0
                        i_theta=i_theta+1;
                    end
                    i_theta2=i_theta-1;
                    thetabbo=thetaop(1,i_theta2)-thetaop(1,i_theta1);
                    for i_theta = i_theta1:i_theta2
                        i_r = 1;
                        while Gucs+Sp3op(i_r,i_theta)*(1+sin(Gfri))/(1-sin(Gfri))-Sp1op(i_r,i_theta)<=0
                            i_r=i_r+1;
                        end
                        if rop(i_r-1,1)>rbbo
                            rbbo=rop(i_r-1,1);
                        end
                    end
                end
            end
end
