% AUTO-GENERATED by tools/make_reference_dfn_m.py - do not edit.
% Run from repo root:  matlab -batch "run('tools/gen_reference_dfn.m')"
root = fileparts(fileparts(mfilename('fullpath')));
out = struct();
% cases: seed n x0 y0 z0 domx domy domz dip dipd K len fsize_ne fracd trim curt apmean  (Circle, neg-exp aperture)
C = [1 60 10 10 10 0 0 5 45 90 20 2 1 2.5 0.5 10 100;
     7 40 20 15 10 2 -1 8 70 200 8 3 0 2.5 0.5 10 50;
     3 80 10 10 10 0 0 5 10 30 50 1.5 1 2.5 0.5 10 100];
for k = 1:size(C, 1)
    c = num2cell(C(k, :));
    [seed, n, x0, y0, z0, domx, domy, domz, dipdeg, dipddeg, K, l, fsize_ne, fracd, trim, curt, apmean] = c{:};
    rng(seed, 'twister');
    [x1, y1, z1, l1, ap, rfk, Pf, dip2, dipd2, CC, K2] = dfn_gener('Circle', n, x0, y0, z0, domx, domy, domz, ...
        dipdeg*pi/180, dipddeg*pi/180, K, l, fsize_ne, fracd, trim, curt, apmean);
    out.cases(k).inputs = C(k, :);
    out.cases(k).x1 = x1; out.cases(k).y1 = y1; out.cases(k).z1 = z1; out.cases(k).l1 = l1; out.cases(k).ap = ap;
    out.cases(k).rfk = rfk; out.cases(k).Pf = Pf; out.cases(k).dip2 = dip2; out.cases(k).dipd2 = dipd2; out.cases(k).K2 = K2;
    out.cases(k).CC1 = CC{1}'; out.cases(k).CCend = CC{end}';   % (200 x 3)
    [SW, ok] = dfn_sw(n, l1, dip2, dipd2, x1, y1, z1, 60*pi/180, 30*pi/180, 0.5);
    out.cases(k).sw_ok = ok; out.cases(k).SW = SW;   % (n x 6): x1 y1 z1 x2 y2 z2 (NaN when no intersection)
    inter = dfn_drill(n, CC, x1, y1, z1, dip2, dipd2, l1, domx + 0.5, domy - 0.3, 0.25);
    out.cases(k).inter = inter;
    fprintf('case %d: K2 %.3f, %d window traces, %d drill intersections\n', k, K2, sum(ok), sum(inter));
end
% (the original Square branch fails in MATLAB: Pi2(z,:) = rotx90*Pi(z,:) multiplies a 3x3 by a 1x3)
f = fullfile(root, 'tests', 'reference', 'dfn_matlab.json');
fid = fopen(f, 'w'); fwrite(fid, jsonencode(out), 'char'); fclose(fid);
fprintf('wrote %s\n', f);

% =====================================================================
function [x1, y1, z1, l1, ap, rfk, Pf, dip2, dipd2, CC, K2] = dfn_gener(shape, n, x0, y0, z0, domx, domy, domz, dip, dipd, K, l, fsize_ne, fracd, trim, curt, apmean)
    temp3pop = shape; temp1pop = 'Fisher'; temp4pop = 'Negative exponential'; apstdv = 0;
    x1 = []; y1 = []; z1 = []; CC = {};
rfk = 0;
l1 = 0;
ap = 0;
dip2 = 0;
dipd2 = 0;
eqa = 0;
eqb = 0;
eqc = 0;
for z=1:n
x1(z)=domx+x0*rand-x0/2; % 균열 중심의 x,y,z 좌표 결정. 중심의 분포는 domain 내에서 균일 분포
y1(z)=domy+y0*rand-y0/2;
z1(z)=-domz+z0*rand-z0/2;

if fsize_ne  % 균열 길이 분포
    l1(z) = -log(1-rand)*l;
else
    l1(z) = ((trim)^(-fracd)-((trim)^(-fracd)-(curt)^(-fracd))*rand)^(-1/fracd); 
end

if strcmp(temp4pop,'Negative exponential') % 균열 간극 분포 입력
    ap(z) = -log(1-rand)*apmean;
elseif strcmp(temp4pop,'Normal')
    ap(z) = normrnd(apmean,apstdv);
elseif strcmp(temp4pop,'Log normal')
    ap(z) = lognrnd(log(l^2/(sqrt(apstdv+apmean^2))),sqrt(log(apstdv/apmean^2+1)));
elseif strcmp(temp4pop,'Uniform')
    ap(z) = apmean*2*rand;
end

if strcmp(temp3pop,'Square')

if strcmp(temp1pop,'Fisher') % 균열 방향분포
    rotx = [1 0 0; 0 cos(-dip) -sin(-dip); 0 sin(-dip) cos(-dip)]; % Dip (x축 회전) 시계방향이라서 (-dip)
    rotx90 = [1 0 0; 0 cos(-pi/2) -sin(-pi/2); 0 sin(-pi/2) cos(-pi/2)]; 
    rotz = [cos(-dipd) -sin(-dipd) 0; sin(-dipd) cos(-dipd) 0; 0 0 1]; % Dip direction (z축 회전) 시계방향이라서 (-dipd)
    rfk = 0;
    rfk(z) = acos((log(1-rand))/K + 1); % Fisher 분포를 따르는 임의의 각도 생성
    N = rotz*(rotx*[0 0 1]'); % Dip/Dip direction이 0도 일 때 기준으로 dip/dip direction 만큼 노말벡터를 회전.
    r1 = -1+2*rand;
    q = rand;
        if q > 0.5
        q = 1;
        else
        q = -1;
        end
    Pi(z,:) = [r1*sin(rfk(z)) q*sqrt(sin(rfk(z))^2-(r1*sin(rfk(z)))^2) cos(rfk(z))]; % 기준상태일 때 호위의 임의의 점
    Pi2(z,:) = rotx90*Pi(z,:);
    Pf(z,:) = rotz*(rotx*Pi(z,:)'); % dip/dip direction만큼 회전시켰을 때 호위의 임의의 점

    a(z)=asin(sqrt(Pf(z,1)^2+Pf(z,2)^2)); 
    if Pf(z,1) > 0 & Pf(z,2) > 0
    b(z)=atan(Pf(z,1)/Pf(z,2));
    elseif Pf(z,1) > 0 & Pf(z,2) < 0
    b(z)=pi/2-atan(Pf(z,1)/Pf(z,2));
    elseif Pf(z,1) < 0 & Pf(z,2) < 0
    b(z)=atan(Pf(z,1)/Pf(z,2))+pi;
    elseif Pf(z,1) < 0 & Pf(z,2) > 0
    b(z)=3*pi/2-atan(Pf(z,1)/Pf(z,2));
    end
end
v1=[x1(z)+l1(z)*sqrt(2)/2*cos(a(z))*cos(-(b(z)+pi/4)) y1(z)+l1(z)*sqrt(2)/2*cos(a(z))*sin(-(b(z)+pi/4)) z1(z)-sqrt(2)/2*sin(a(z))];
v2=[x1(z)+l1(z)*sqrt(2)/2*cos(a(z))*cos(-(b(z)+pi*3/4)) y1(z)+l1(z)*sqrt(2)/2*cos(a(z))*sin(-(b(z)+pi*3/4)) z1(z)+sqrt(2)/2*sin(a(z))];
v3=[x1(z)+l1(z)*sqrt(2)/2*cos(a(z))*cos(-(b(z)+pi*5/4)) y1(z)+l1(z)*sqrt(2)/2*cos(a(z))*sin(-(b(z)+pi*5/4)) z1(z)+sqrt(2)/2*sin(a(z))];
v4=[x1(z)+l1(z)*sqrt(2)/2*cos(a(z))*cos(-(b(z)+pi*7/4)) y1(z)+l1(z)*sqrt(2)/2*cos(a(z))*sin(-(b(z)+pi*7/4)) z1(z)-sqrt(2)/2*sin(a(z))];

vertex=[v1;v2;v3;v4];
face=[1 2 3 4];

elseif strcmp(temp3pop,'Circle')
if strcmp(temp1pop,'Fisher')
    % K is an argument
    rotx = [1 0 0; 0 cos(-dip) -sin(-dip); 0 sin(-dip) cos(-dip)]; % Dip (x축 회전) 시계방향이라서 (-dip) 
    rotz = [cos(-dipd) -sin(-dipd) 0; sin(-dipd) cos(-dipd) 0; 0 0 1]; % Dip direction (z축 회전) 시계방향이라서 (-dipd)
    rfk(z) = acos((log(1-rand))/K + 1); % Fisher 분포를 따르는 임의의 각도 생성
    N = rotz*(rotx*[0 0 1]'); % Dip/Dip direction이 0도 일 때 기준으로 dip/dip direction 만큼 노말벡터를 회전.
    rtheta(z) = rand*2*pi;
    q = rand;
        if q > 0.5
        q = 1;
        else
        q = -1;
        end
    Pi(z,:) = [sin(rfk(z))*cos(rtheta(z)) sin(rfk(z))*sin(rtheta(z)) cos(rfk(z))]; % 기준상태일 때 호위의 임의의 점
    Pf(z,:) = rotz*(rotx*Pi(z,:)'); % dip/dip direction만큼 회전시켰을 때 호위의 임의의 점  
    dip2(z) = 0;
    dip2(z) = acos(Pf(z,3));
    if Pf(z,3) < 0
        Pf(z,1) = -Pf(z,1);
        Pf(z,2) = -Pf(z,2);
        dip2(z) = -dip2(z);
    end
    if Pf(z,1) >= 0 && Pf(z,2) >= 0
        dipd2(z) = atan(Pf(z,1)/Pf(z,2));
    elseif Pf(z,1) >= 0 && Pf(z,2) < 0
        dipd2(z) = atan(-Pf(z,2)/Pf(z,1)) + pi/2;
    elseif Pf(z,1) < 0 && Pf(z,2) >= 0
        dipd2(z) = atan(-Pf(z,2)/Pf(z,1)) + pi*3/2;
    elseif Pf(z,1) < 0 && Pf(z,2) < 0
        dipd2(z) = atan(Pf(z,1)/Pf(z,2)) + pi;
    end
    if dip2(z) <= -pi/2
        dip2(z) = pi+dip2(z);
        dipd2(z) = abs(2*pi-dipd2(z));
    end
rotx2{z} = [1 0 0; 0 cos(-dip2(z)) -sin(-dip2(z)); 0 sin(-dip2(z)) cos(-dip2(z))];
rotz2{z} = [cos(-dipd2(z)) -sin(-dipd2(z)) 0; sin(-dipd2(z)) cos(-dipd2(z)) 0; 0 0 1];
rotx3{z} = [1 0 0; 0 cos(dip2(z)) -sin(dip2(z)); 0 sin(dip2(z)) cos(dip2(z))];
rotz3{z} = [cos(dipd2(z)) -sin(dipd2(z)) 0; sin(dipd2(z)) cos(dipd2(z)) 0; 0 0 1];
P1{z} = [x1(z) y1(z) z1(z)]';
P2{z} = (rotx3{z}*(rotz3{z}*P1{z}))';
end

i=1:200;
NP{z}(i,1) = P2{z}(1)+l1(z)/2*cos(2*pi/200*i);
NP{z}(i,2) = P2{z}(2)+l1(z)/2*sin(2*pi/200*i);
NP{z}(i,3) = P2{z}(3);
CC{z} = rotz2{z}*(rotx2{z}*NP{z}'); 
% 속이 찬 원 그리기
end
end

rnx = sum(Pf(:,1));
rny = sum(Pf(:,2));
rnz = sum(Pf(:,3));
rn = sqrt(rnx^2+rny^2+rnz^2);
K2 = (n-1)/(n-rn);
    if strcmp(shape, 'Square')
        CC = cell(1, n);
        for z = 1:n
            % re-create the square vertices exactly as the loop did (they were only drawn)
            v1=[x1(z)+l1(z)*sqrt(2)/2*cos(a(z))*cos(-(b(z)+pi/4)) y1(z)+l1(z)*sqrt(2)/2*cos(a(z))*sin(-(b(z)+pi/4)) z1(z)-sqrt(2)/2*sin(a(z))];
            v2=[x1(z)+l1(z)*sqrt(2)/2*cos(a(z))*cos(-(b(z)+pi*3/4)) y1(z)+l1(z)*sqrt(2)/2*cos(a(z))*sin(-(b(z)+pi*3/4)) z1(z)+sqrt(2)/2*sin(a(z))];
            v3=[x1(z)+l1(z)*sqrt(2)/2*cos(a(z))*cos(-(b(z)+pi*5/4)) y1(z)+l1(z)*sqrt(2)/2*cos(a(z))*sin(-(b(z)+pi*5/4)) z1(z)+sqrt(2)/2*sin(a(z))];
            v4=[x1(z)+l1(z)*sqrt(2)/2*cos(a(z))*cos(-(b(z)+pi*7/4)) y1(z)+l1(z)*sqrt(2)/2*cos(a(z))*sin(-(b(z)+pi*7/4)) z1(z)-sqrt(2)/2*sin(a(z))];
            CC{z} = [v1; v2; v3; v4];
        end
        dip2 = zeros(1, n); dipd2 = zeros(1, n);
    end
end

function [SWout, ok] = dfn_sw(n, l1, dip2, dipd2, x1, y1, z1, swdip, swdipd, swd)
    for z = 1:n
        rotx2{z} = [1 0 0; 0 cos(-dip2(z)) -sin(-dip2(z)); 0 sin(-dip2(z)) cos(-dip2(z))];
        rotz2{z} = [cos(-dipd2(z)) -sin(-dipd2(z)) 0; sin(-dipd2(z)) cos(-dipd2(z)) 0; 0 0 1];
        rotx3{z} = [1 0 0; 0 cos(dip2(z)) -sin(dip2(z)); 0 sin(dip2(z)) cos(dip2(z))];
        rotz3{z} = [cos(dipd2(z)) -sin(dipd2(z)) 0; sin(dipd2(z)) cos(dipd2(z)) 0; 0 0 1];
        P1{z} = [x1(z) y1(z) z1(z)]';
        P2{z} = (rotx3{z}*(rotz3{z}*P1{z}))';
    end
for z = 1:n
SWV = [sin(swdip)*sin(swdipd) sin(swdip)*cos(swdipd) cos(swdip)]';
TSWV = (rotx3{z}*(rotz3{z}*SWV))';

temp3{z} = (rotx3{z}*(rotz3{z}*[0 0 swd/SWV(3)]'))';

swa(z) = TSWV(1);
swb(z) = TSWV(2);
swc(z) = TSWV(3);
swd2(z) = swa(z)*temp3{z}(1)+swb(z)*temp3{z}(2)+swc(z)*temp3{z}(3);

eqa(z) = 1+(swa(z)/swb(z))^2;
eqb(z) = -2*P2{z}(1)+2*swa(z)*swc(z)*P2{z}(3)/(swb(z)^2)-2*swa(z)*swd2(z)/(swb(z)^2)+2*swa(z)*P2{z}(2)/swb(z);
eqc(z) = P2{z}(1)^2+(swc(z)*P2{z}(3)/swb(z))^2+(swd2(z)/swb(z))^2+P2{z}(2)^2-2*swc(z)*swd2(z)*P2{z}(3)/(swb(z)^2)+2*swc(z)*P2{z}(2)*P2{z}(3)/swb(z)-2*swd2(z)*P2{z}(2)/swb(z)-(l1(z)^2)/4;

swx1(z) = (-eqb(z)-sqrt(eqb(z)^2-4*eqa(z)*eqc(z)))/(2*eqa(z));
swy1(z) = (-swa(z)*swx1(z)+swd2(z)-swc(z)*P2{z}(3))/swb(z);
swx2(z) = (-eqb(z)+sqrt(eqb(z)^2-4*eqa(z)*eqc(z)))/(2*eqa(z));
swy2(z) = (-swa(z)*swx2(z)+swd2(z)-swc(z)*P2{z}(3))/swb(z);

temp1 = [swx1(z) swy1(z) P2{z}(3)]';
temp2 = [swx2(z) swy2(z) P2{z}(3)]';

SW{z} = [(rotz2{z}*(rotx2{z}*temp1))';(rotz2{z}*(rotx2{z}*temp2))'];
rotx4{z} = [1 0 0; 0 cos(swdip-pi/2) -sin(swdip-pi/2); 0 sin(swdip-pi/2) cos(swdip-pi/2)];
rotz4{z} = [cos(swdipd) -sin(swdipd) 0; sin(swdipd) cos(swdipd) 0; 0 0 1];
SW2{z} = rotx4{z}*(rotz4{z}*SW{z}');
end
    SWout = nan(n, 6); ok = zeros(1, n);
    for z = 1:n
        if eqb(z)^2-4*eqa(z)*eqc(z) >= 0
            ok(z) = 1; SWout(z, :) = [SW{z}(1,:) SW{z}(2,:)];
        end
    end
end

function inter = dfn_drill(n, CC, x1, y1, z1, dip2, dipd2, l1, drillx, drilly, drillr)
    for z = 1:n, P1{z} = [x1(z) y1(z) z1(z)]'; end
    inter = zeros(1, n);
    for z=1:n
    sqrt((drillx-P1{z}(1))^2+(drilly-P1{z}(2))^2)/cos(dip2(z));
for i=1:200
if (CC{z}(1,i)-drillx)^2+(CC{z}(2,i)-drilly)^2 < drillr^2 
    nn(i)=1;
else
    nn(i)=0;
end
end
nx(z) = sin(dip2(z))*sin(dipd2(z));
ny(z) = sin(dip2(z))*cos(dipd2(z));
nz(z) = cos(dip2(z));
dz(z) = (nx(z)*P1{z}(1)+ny(z)*P1{z}(2)+nz(z)*P1{z}(3)-nx(z)*drillx-ny(z)*drilly)/nz(z);
theta(z) = atan(abs(dz(z)-P1{z}(3))/sqrt((drillx-P1{z}(1))^2+(drilly-P1{z}(2))^2));
if sqrt((drillx-P1{z}(1))^2+(drilly-P1{z}(2))^2)/cos(theta(z)) < l1(z)/2-drillr/cos(theta(z))
    mm(z)=1;
else
    mm(z)=0;
end

    inter(z) = (sum(nn) > 0) || (mm(z) == 1);
    end
end
