% AUTO-GENERATED by tools/make_reference_hydroshear_m.py - do not edit.
% Run from repo root:  matlab -batch "run('tools/gen_reference_hydroshear.m')"
root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(root, 'src'));
out = struct();
% cases: Sv SHmax Shmin SHmax_azi(deg) phi(deg) rho_r rho_f alpha
C = [30 40 25 0 30 2600 1000 0.5;
     30 45 20 60 35 2650 1000 0.3;
     30 28 20 120 30 2500 1050 0.5;
     30 50 32 30 25 2700 1000 0.7];
J = [75.285858 151.938677; 60.189236 23.554691; 65.528164 174.726243; 33.26572 153.418764; 0 0; 90 45; 45 270];
for k = 1:size(C, 1)
    c = C(k, :);
    Svmag = c(1)*1e6; SHmaxmag = c(2)*1e6; Shminmag = c(3)*1e6; SHmaxazi = c(4)*pi/180; phi = c(5)*pi/180;
    rho_r = c(6); rho_f = c(7); alpha = c(8);
    S123 = strSort(Svmag, SHmaxmag, SHmaxazi, Shminmag);
    Pcm = Pcm_cal(S123(1,1), S123(3,1), phi);
    Pco = Pco_cal(Pcm, alpha, S123(3,1));
    [t1, t2] = optJD(S123, phi);
    Pc = zeros(size(J,1),1); grad = zeros(size(J,1),1);
    for i = 1:size(J,1)
        Pc(i) = Pc_cal2(J(i,1)*pi/180, J(i,2)*pi/180, S123, phi);
        grad(i) = dPcdz_cal(rho_r, J(i,1)*pi/180, J(i,2)*pi/180, S123, Svmag, phi);
    end
    [x, y, kcm, kco, pro_pco, pro_down] = hs_polygon(phi, Svmag, rho_r, rho_f, alpha, 1, 1);
    [kc, pp_gr, sx, sy, p, prob] = hs_stereonet(S123, Svmag, phi, rho_r, rho_f, alpha, 1);
    out.cases(k).inputs = c; out.cases(k).joints = J;
    out.cases(k).S123 = S123; out.cases(k).Pcm = Pcm; out.cases(k).Pco = Pco;
    out.cases(k).opt1 = t1; out.cases(k).opt2 = t2; out.cases(k).Pc = Pc(:)'; out.cases(k).grad = grad(:)';
    out.cases(k).poly_x = x; out.cases(k).poly_y = y; out.cases(k).kcm = kcm; out.cases(k).kco = kco;
    out.cases(k).pro_pco = pro_pco; out.cases(k).pro_down = pro_down;
    si = 1:20:361; sj = 1:10:91;
    out.cases(k).si = si-1; out.cases(k).sj = sj-1;
    out.cases(k).kc = kc(si, sj); out.cases(k).pp_gr = pp_gr(si, sj); out.cases(k).sx = sx(si, sj); out.cases(k).sy = sy(si, sj);
    out.cases(k).p = p(:)'; out.cases(k).prob = prob(:)';
    fprintf('case %d: Pcm %.4f Pco %.4f opt %s %s prob(end) %.4f\n', k, Pcm/1e6, Pco/1e6, t1, t2, prob(end));
end
f = fullfile(root, 'tests', 'reference', 'hydroshear_matlab.json');
fid = fopen(f, 'w'); fwrite(fid, jsonencode(out), 'char'); fclose(fid);
fprintf('wrote %s\n', f);

function [x, y, kcm, kco, pro_pco, pro_down] = hs_polygon(phi, Svmag, rho_r, rho_f, alpha, PcoCheck, probDownCheck)
n = 50; % number of nodes on each boundaries of stress polygon
k0=rho_f/rho_r; % normalized hydrostatic pressure gradient

%% variable defining %%
x=zeros(n,n); %shmin coordinate of contour plot
y=zeros(n,n);%shmax coordinate of contour plot
str1=zeros(3);% field principal stress
kcm=zeros(n,n);% pressure for shearing most optimally oriented fracture
kco=zeros(n,n);% normalized cut-off pressure
pro_pco=zeros(n,n); % shearing probability by Pco
pro_down=zeros(n,n);% downward slip probability
pp=zeros(91,91);%pressure for slip

%% mu-, mu+ for stress polygon boundary definition
mu = tan(phi);
mup=sqrt(mu^2+1)+mu; % mu+
mum=sqrt(mu^2+1)-mu; % mu-

%% main computing
for i = 1:n
    for j = 1:n
        sfDown=0; %downward slip fracture number
        if j == n
            x(i, n) = mum/mup;
            y(i, n) = x(i, n) * (1 + (i-1)/(n-1)*(mup/mum-1));
        else
            x(i, j) = (mum/mup*tan(pi/2*(j-1)/(n-1)) + mup/mum) / (1 + (i-1)/(n-1)*(mup/mum-1) +tan(pi/2*(j-1)/(n-1)));
            y(i, j) = x(i, j) * (1 + (i-1)/(n-1)*(mup/mum-1));
        end
        sig = sort([y(i, j) x(i, j) 1], 'descend');
        kcm(i, j) = Pcm_cal(sig(1)*Svmag/1000000,sig(3)*Svmag/1000000, phi) / Svmag*1000000;
        
        str1(3,3)=1.0;% vertical stress
        str1(1,1)=y(i,j);% shmi
        str1(2,2)=x(i,j);% shma
        
        if PcoCheck == 1 || probDownCheck == 1
            
            kco(i,j) = kcm(i,j) + alpha*(sig(3) - kcm(i,j));
            sfPco = 0; %slip fracture number
            
            counter1 = 0;
            counter2 = 0;
            
            for k = 1:90
                did = 4*(k-1)/180*pi;
                for h = 1:91
                    di = (h-1)/180*pi;
                    nv = [-sin(di)*cos(did); -sin(di)*sin(did); cos(di)];
                    tr=str1*nv; % fracture traction vector
                    nor=dot(tr,nv); %fracture normal stress
                    she=sqrt(dot(tr,tr)-nor*nor);%joint shear stress
                    pp(k,h)=nor-she/tan(phi); %required pressure for slip
                    
                    if h==1
                        counter1 = counter1+1; % counter for dip = 0 deg.
                    end
                    if h==91
                        counter2 = counter2+1; % counter for dip = 90 deg.
                    end
                    
                    if (h==1&&counter1<2) || (h==91&&counter2<46) || (h>1&&h<91)
                        if (pp(k,h)-kco(i,j))<0
                            sfPco=sfPco+1;
                        end
                        if (pp(k, h) - k0) < 0
                            sfDown = sfDown + 1;
                        end
                    end
                end
            end
            if (kcm(i,j)-k0)>=0
                sfDown=0;
            end
            pro_down(i,j)=sfDown/(90*89+45+1);
            pro_pco(i,j)=sfPco/(90*89+45+1);
        end
    end
end
end

function [kc, pp_gr, x, y, p, prob] = hs_stereonet(S123, Svmag, phi, rho_r, rho_f, alpha, PcCheck)
%% variable definition
S1 = S123(1, 1); % S1 magnitude
S2 = S123(2, 1); % S2 magnitude
S3 = S123(3, 1); % S3 magnitude
S1_d = S123(1, 2:4); % direction of S1
S2_d = S123(2, 2:4); % direction of S2
S3_d = S123(3, 2:4); % direction of S3

Pcm = Pcm_cal(S1, S3, phi); % minimum critical pressure for shearing
Pco = Pco_cal(Pcm, alpha, S3); % cut-off pressure for shearing

nor_sig3 = S3/Svmag;
nor_sig1 = S1/Svmag;
nor_Pco = Pco/Svmag;
nor_Pcm = Pcm/Svmag;

gr_sv=rho_r/100*0.980665;% vertical stress gradient
gr_f=rho_f/100*0.980665;% hydrostatic pressure gradient
%gr_f=roundn(gr_f,-2);

kc = zeros(361,91);% normalized pc
pp_gr=zeros(361,91);% pressure gradient
x=zeros(361,91);% lower hemisphere projection
y=zeros(361,91);% lower hemisphere projection

no=91;
p = zeros(no); % pressure interval used to compute No. of poles assume 90 intervals
num_fra = zeros(no);%number of fracures within pressure interval
prob = zeros(no);%cumulative probability of shearing with respect to the increasing pressure

%% main computation
if PcCheck == 1
    dp = (nor_sig1 - nor_Pcm)/(no-1);
    for i=1:no
        p(i) = nor_Pcm + (i-1)*dp;
    end
end

counter1 = 0;
counter2 = 0;

for i=1:360
    did = (i-1)/180*pi; % dip direction
    tre = did + pi;% trend of joint normal pole
    for j=1:91
        di = (j-1)/180*pi; % dip
        plu = 0.5*pi-di; % plunge
        jNormal = [sin(di)*sin(did) sin(di)*cos(did) cos(di)];
        l = dot(jNormal, S1_d)/norm(jNormal); % direction cosine to S1
        m = dot(jNormal, S2_d)/norm(jNormal); % direction cosine to S2
        n = dot(jNormal, S3_d)/norm(jNormal); % direction cosine to S3
        sigma = l^2*S1 + m^2*S2 + n^2*S3; % resolved normal stress
        tau = sqrt(((S1-S2)*l*m)^2 + ((S2-S3)*m*n)^2 + ((S3-S1)*n*l)^2); % resolved shear stress
        kc(i, j) = (sigma - tau/tan(phi))/Svmag; % normalized critical pressure for shearing
        pp_gr(i, j) = kc(i, j)*gr_sv; % normalized gradient of critical pressure
        x(i, j) = sqrt(2)*cos(tre)*cos(0.5*(0.5*pi+plu)); % calculated as equal-area stereonet
        y(i, j) = sqrt(2)*sin(tre)*cos(0.5*(0.5*pi+plu));
        
        if j==1
            counter1 = counter1+1; % counter for dip = 0 deg.
        end
        if j==91
            counter2 = counter2+1; % counter for dip = 90 deg.
        end
        
        if PcCheck==1
            if (j==1&&counter1<2) || (j==91&&counter2<181) || (j>1&&j<91)
                k = 1;
                while 1
                    if k == no
                        break
                    end
                    if (kc(i, j)>=p(k) && kc(i, j)<p(k + 1)) || (k==no-1 && kc(i,j)==p(k+1))
                        num_fra(k) = num_fra(k) + 1; % number of joints sheared by p(k)
                    elseif kc(i, j) < p(k)
                        break
                    end
                    k = k + 1;
                end
            end
        end
        
     end
end

kc(361,:) = kc(1,:);
pp_gr(361,:) = pp_gr(1,:);
x(361,:) = x(1,:);
y(361,:) = y(1,:);

if PcCheck == 1
    prob(2) = num_fra(1);
    for i = 3:no
        prob(i) = prob(i-1) + num_fra(i-1);
    end
    prob = prob/(360*89+180+1);
end
end
