"""Builds tools/gen_reference_dfn.m from threeddfngui.m: the generation loop, the
sampling-window intersection and the drillhole classification are sliced verbatim
(graphics lines removed, GUI reads replaced by function arguments). Random numbers
come from rng(seed, 'twister'), which numpy's RandomState(seed) reproduces exactly.

    python tools/make_reference_dfn_m.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = (ROOT / "src" / "threeddfngui.m").read_bytes().decode("cp949", errors="replace").splitlines()
GRAPHICS = re.compile(r"^\s*(figure\(|patch\(|fill3\(|view\(|grid on|hold on|hold off|alpha |rotate3d|daspect|title\(|xlabel\(|ylabel\(|zlabel\(|surf\(|plot3\(|plot\(|subplot\(|mesh\(|axis |save\(|tic|toc)")


def lines(a: int, b: int) -> str:
    return "\n".join(l for l in SRC[a - 1:b] if not GRAPHICS.match(l))


gener = (lines(266, 410).replace("get(handles.fsize_ne, 'value')", "fsize_ne")
         .replace("K = str2double(get(handles.fisherk,'String'));", "% K is an argument"))
sw = lines(517, 544)
drill = lines(753, 771)   # loop body only; the wrapper opens the for-loop

m = f"""% AUTO-GENERATED by tools/make_reference_dfn_m.py - do not edit.
% Run from repo root:  matlab -batch "run('tools/gen_reference_dfn.m')"
root = fileparts(fileparts(mfilename('fullpath')));
out = struct();
% cases: seed n x0 y0 z0 domx domy domz dip dipd K len fsize_ne fracd trim curt apmean  (Circle, neg-exp aperture)
C = [1 60 10 10 10 0 0 5 45 90 20 2 1 2.5 0.5 10 100;
     7 40 20 15 10 2 -1 8 70 200 8 3 0 2.5 0.5 10 50;
     3 80 10 10 10 0 0 5 10 30 50 1.5 1 2.5 0.5 10 100];
for k = 1:size(C, 1)
    c = num2cell(C(k, :));
    [seed, n, x0, y0, z0, domx, domy, domz, dipdeg, dipddeg, K, l, fsize_ne, fracd, trim, curt, apmean] = c{{:}};
    rng(seed, 'twister');
    [x1, y1, z1, l1, ap, rfk, Pf, dip2, dipd2, CC, K2] = dfn_gener('Circle', n, x0, y0, z0, domx, domy, domz, ...
        dipdeg*pi/180, dipddeg*pi/180, K, l, fsize_ne, fracd, trim, curt, apmean);
    out.cases(k).inputs = C(k, :);
    out.cases(k).x1 = x1; out.cases(k).y1 = y1; out.cases(k).z1 = z1; out.cases(k).l1 = l1; out.cases(k).ap = ap;
    out.cases(k).rfk = rfk; out.cases(k).Pf = Pf; out.cases(k).dip2 = dip2; out.cases(k).dipd2 = dipd2; out.cases(k).K2 = K2;
    out.cases(k).CC1 = CC{{1}}'; out.cases(k).CCend = CC{{end}}';   % (200 x 3)
    [SW, ok] = dfn_sw(n, l1, dip2, dipd2, x1, y1, z1, 60*pi/180, 30*pi/180, 0.5);
    out.cases(k).sw_ok = ok; out.cases(k).SW = SW;   % (n x 6): x1 y1 z1 x2 y2 z2 (NaN when no intersection)
    inter = dfn_drill(n, CC, x1, y1, z1, dip2, dipd2, l1, domx + 0.5, domy - 0.3, 0.25);
    out.cases(k).inter = inter;
    fprintf('case %d: K2 %.3f, %d window traces, %d drill intersections\\n', k, K2, sum(ok), sum(inter));
end
% (the original Square branch fails in MATLAB: Pi2(z,:) = rotx90*Pi(z,:) multiplies a 3x3 by a 1x3)
f = fullfile(root, 'tests', 'reference', 'dfn_matlab.json');
fid = fopen(f, 'w'); fwrite(fid, jsonencode(out), 'char'); fclose(fid);
fprintf('wrote %s\\n', f);

% =====================================================================
function [x1, y1, z1, l1, ap, rfk, Pf, dip2, dipd2, CC, K2] = dfn_gener(shape, n, x0, y0, z0, domx, domy, domz, dip, dipd, K, l, fsize_ne, fracd, trim, curt, apmean)
    temp3pop = shape; temp1pop = 'Fisher'; temp4pop = 'Negative exponential'; apstdv = 0;
    x1 = []; y1 = []; z1 = []; CC = {{}};
{gener}
    if strcmp(shape, 'Square')
        CC = cell(1, n);
        for z = 1:n
            % re-create the square vertices exactly as the loop did (they were only drawn)
            v1=[x1(z)+l1(z)*sqrt(2)/2*cos(a(z))*cos(-(b(z)+pi/4)) y1(z)+l1(z)*sqrt(2)/2*cos(a(z))*sin(-(b(z)+pi/4)) z1(z)-sqrt(2)/2*sin(a(z))];
            v2=[x1(z)+l1(z)*sqrt(2)/2*cos(a(z))*cos(-(b(z)+pi*3/4)) y1(z)+l1(z)*sqrt(2)/2*cos(a(z))*sin(-(b(z)+pi*3/4)) z1(z)+sqrt(2)/2*sin(a(z))];
            v3=[x1(z)+l1(z)*sqrt(2)/2*cos(a(z))*cos(-(b(z)+pi*5/4)) y1(z)+l1(z)*sqrt(2)/2*cos(a(z))*sin(-(b(z)+pi*5/4)) z1(z)+sqrt(2)/2*sin(a(z))];
            v4=[x1(z)+l1(z)*sqrt(2)/2*cos(a(z))*cos(-(b(z)+pi*7/4)) y1(z)+l1(z)*sqrt(2)/2*cos(a(z))*sin(-(b(z)+pi*7/4)) z1(z)-sqrt(2)/2*sin(a(z))];
            CC{{z}} = [v1; v2; v3; v4];
        end
        dip2 = zeros(1, n); dipd2 = zeros(1, n);
    end
end

function [SWout, ok] = dfn_sw(n, l1, dip2, dipd2, x1, y1, z1, swdip, swdipd, swd)
    for z = 1:n
        rotx2{{z}} = [1 0 0; 0 cos(-dip2(z)) -sin(-dip2(z)); 0 sin(-dip2(z)) cos(-dip2(z))];
        rotz2{{z}} = [cos(-dipd2(z)) -sin(-dipd2(z)) 0; sin(-dipd2(z)) cos(-dipd2(z)) 0; 0 0 1];
        rotx3{{z}} = [1 0 0; 0 cos(dip2(z)) -sin(dip2(z)); 0 sin(dip2(z)) cos(dip2(z))];
        rotz3{{z}} = [cos(dipd2(z)) -sin(dipd2(z)) 0; sin(dipd2(z)) cos(dipd2(z)) 0; 0 0 1];
        P1{{z}} = [x1(z) y1(z) z1(z)]';
        P2{{z}} = (rotx3{{z}}*(rotz3{{z}}*P1{{z}}))';
    end
{sw}
    SWout = nan(n, 6); ok = zeros(1, n);
    for z = 1:n
        if eqb(z)^2-4*eqa(z)*eqc(z) >= 0
            ok(z) = 1; SWout(z, :) = [SW{{z}}(1,:) SW{{z}}(2,:)];
        end
    end
end

function inter = dfn_drill(n, CC, x1, y1, z1, dip2, dipd2, l1, drillx, drilly, drillr)
    for z = 1:n, P1{{z}} = [x1(z) y1(z) z1(z)]'; end
    inter = zeros(1, n);
    for z=1:n
{drill}
    inter(z) = (sum(nn) > 0) || (mm(z) == 1);
    end
end
"""
(ROOT / "tools" / "gen_reference_dfn.m").write_text(m, encoding="utf-8")
print("wrote tools/gen_reference_dfn.m")
