"""Builds tools/gen_reference_borehole.m by extracting the computational blocks of
src/BSA210831_v2.m verbatim (analytic solution, FEM, breakout geometry) and wrapping
them in plain functions, so the MATLAB reference is produced by the original code.

    python tools/make_reference_borehole_m.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = (ROOT / "src" / "BSA210831_v2.m").read_bytes().decode("cp949", errors="replace").splitlines()


def lines(a: int, b: int) -> str:
    """1-based inclusive line range."""
    return "\n".join(SRC[a - 1:b])


analytic = lines(464, 731).replace("if get(handles.RadAna, 'value')==1", "if true")
fem = lines(744, 1010)
bbo = lines(1681, 1720)

m = f"""% AUTO-GENERATED by tools/make_reference_borehole_m.py - do not edit.
% Computational blocks of src/BSA210831_v2.m wrapped as functions, plus calUCS/calOBB.
% Run from repo root:  matlab -batch "run('tools/gen_reference_borehole.m')"
root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(root, 'src'));
out = struct();

% ---------------- single orientation, analytic ----------------
iso = [1/100 -0.25/100 -0.25/100 0 0 0; -0.25/100 1/100 -0.25/100 0 0 0; -0.25/100 -0.25/100 1/100 0 0 0; ...
       0 0 0 2*1.25/100 0 0; 0 0 0 0 2*1.25/100 0; 0 0 0 0 0 2*1.25/100];
E=60; E_=40; v=0.25; v_=0.2; G=15;
trans = [1/E -v/E -v_/E_ 0 0 0; -v/E 1/E -v_/E_ 0 0 0; -v_/E_ -v_/E_ 1/E_ 0 0 0; 0 0 0 1/G 0 0; 0 0 0 0 1/G 0; 0 0 0 0 0 2*(1+v)/E];
% cases: {{Gmat, Sx, Sy, Sz, Sxy, Syz, Sxz, Pp, Pmud(or NaN), dT, alpha, Gr, polar, azimuth}}
cases = {{
  iso,   30, 20, 25, 0, 0, 0, 10, NaN, 0, 0, 0.1, 0, 0;
  iso,   30, 20, 25, 5, 2, 3, 10, 15,  0, 0, 0.1, 30, 45;
  iso,   30, 20, 25, 0, 0, 0, 10, 15, 20, 1e-5, 0.1, 60, 120;
  trans, 30, 20, 25, 0, 0, 0, 10, NaN, 0, 0, 0.1, 0, 0;
  trans, 30, 20, 25, 5, 2, 3, 10, 15, 20, 1e-5, 0.1, 30, 45;
}};
ri = 1:10:181; ti = 1:40:721;
for k = 1:size(cases, 1)
    c = cases(k, :);
    [Sr, St, Sz, Trt, Trz, Ttz, Sp1, Sp2, Sp3, dispxx, dispyy, gridr, gridtheta, mu, lbd] = ...
        bsa_analytic(c{{1}}, c{{2}}, c{{3}}, c{{4}}, c{{5}}, c{{6}}, c{{7}}, c{{8}}, c{{9}}, c{{10}}, c{{11}}, c{{12}}, c{{13}}, c{{14}});
    out.analytic(k).inputs = c(2:14);
    out.analytic(k).Gmat = c{{1}};
    out.analytic(k).ri = ri - 1; out.analytic(k).ti = ti - 1;
    out.analytic(k).r = gridr(ri, ti); out.analytic(k).theta = gridtheta(ri, ti);
    out.analytic(k).Sr = Sr(ri, ti); out.analytic(k).St = St(ri, ti); out.analytic(k).Sz = Sz(ri, ti);
    out.analytic(k).Trt = Trt(ri, ti); out.analytic(k).Trz = Trz(ri, ti); out.analytic(k).Ttz = Ttz(ri, ti);
    out.analytic(k).Sp1 = Sp1(ri, ti); out.analytic(k).Sp2 = Sp2(ri, ti); out.analytic(k).Sp3 = Sp3(ri, ti);
    out.analytic(k).dispxx = dispxx(ri, ti); out.analytic(k).dispyy = dispyy(ri, ti);
    out.analytic(k).mu_re = real(mu); out.analytic(k).mu_im = imag(mu);
    out.analytic(k).St_wall = St(1, :);   % full wall profile for breakout geometry
    out.analytic(k).Sp1_wall = Sp1(1, :); out.analytic(k).Sp3_wall = Sp3(1, :);
    % breakout geometry with UCS = 40 MPa, friction 30 deg
    [rbbo, thetabbo] = bsa_bbo(40e6, 30*pi/180, gridtheta, gridr, Sp1, Sp3);
    out.analytic(k).rbbo = rbbo; out.analytic(k).thetabbo = thetabbo;
    fprintf('analytic %d: St wall max %.4f MPa, rbbo %.4f, thetabbo %.2f\\n', k, max(St(1,:))/1e6, rbbo, thetabbo*180/pi);
end

% ---------------- single orientation, FEM (small mesh) ----------------
[srr, stt, srt, xe, ye] = bsa_fem(iso, 30, 20, 25, 5, 0, 0, 10, 15, 0, 0, 0.1, 0, 0, 16, 16);
out.fem.inputs = {{30, 20, 25, 5, 0, 0, 10, 15, 0, 0, 0.1, 0, 0}}; out.fem.rmesh = 16; out.fem.thmesh = 16;
out.fem.srr = srr(:)'; out.fem.stt = stt(:)'; out.fem.srt = srt(:)'; out.fem.xe = xe(:)'; out.fem.ye = ye(:)';
fprintf('fem: stt range %.4f .. %.4f MPa\\n', min(stt)/1e6, max(stt)/1e6);

% ---------------- all orientations (calUCS / calOBB) ----------------
E = 100; v = 0.25;
Gmat=[1/E -v/E -v/E 0 0 0; -v/E 1/E -v/E 0 0 0; -v/E -v/E 1/E 0 0 0; 0 0 0 2*(1+v)/E 0 0; 0 0 0 0 2*(1+v)/E 0; 0 0 0 0 0 2*(1+v)/E];
amatte = Gmat/10^6;
allcases = [30 20 25 10 15 0 0; 35 20 25 10 12 20 1e-5; 25 20 40 10 15 0 0];
for k = 1:size(allcases, 1)
    a = allcases(k, :);
    Pp = a(4); Gfp = a(5) - Pp; Gtc = a(6); Gec = a(7);
    SHmax = a(1)-Pp; Shmin = a(2)-Pp; Sv = a(3)-Pp; Pmud = Pp + Gfp;
    S_g = bsa_Sg(SHmax, Shmin, Sv);
    delta = 0: pi/20: 2*pi; phi = 0: pi/20: pi/2;
    UCS = zeros(length(delta), length(phi));
    for i = 1:length(delta), for j = 1:length(phi)
        UCS(i,j) = calUCS(delta(i), phi(j), Pp, Pmud, v, S_g, amatte, Gtc, Gec);
    end, end
    deltaobb = 0 : pi/12 : 2*pi; phiobb = 0 : pi/12 : pi/2;
    OBB = zeros(length(deltaobb), length(phiobb));
    for i = 1:length(deltaobb), for j = 1:length(phiobb)
        OBB(i,j) = calOBB(deltaobb(i), phiobb(j), Pp, Pmud, v, S_g, amatte, Gtc, Gec);
    end, end
    out.allori(k).inputs = a; out.allori(k).S_g = S_g; out.allori(k).UCS = UCS; out.allori(k).OBB = OBB;
    fprintf('allori %d: UCS %.4f .. %.4f\\n', k, min(UCS(:)), max(UCS(:)));
end

f = fullfile(root, 'tests', 'reference', 'borehole_matlab.json');
fid = fopen(f, 'w'); fwrite(fid, jsonencode(out), 'char'); fclose(fid);
fprintf('wrote %s\\n', f);

% =====================================================================
function S_g = bsa_Sg(SHmax, Shmin, Sv)
{lines(1210, 1256)}
end

function [Sr, St, Sz, Trt, Trz, Ttz, Sp1, Sp2, Sp3, dispxx, dispyy, gridr, gridtheta, mu, lbd] = ...
        bsa_analytic(Gmat, Sx, Sy, Sz_, Sxy, Syz, Sxz, Gpp, Pmud, Gtc, Gec, Gr, polardeg, azideg)
    amatte = Gmat/10^6;
    Gsxi=(Sx-Gpp)*10^6; Gsyi=(Sy-Gpp)*10^6; Gszi=(Sz_-Gpp)*10^6;
    Gsxyi=Sxy*10^6; Gsyzi=Syz*10^6; Gsxzi=Sxz*10^6;
    Gfp=0; if ~isnan(Pmud), Gfp=(Pmud-Gpp)*10^6; end
    Gpol=polardeg*2*pi/360; Gazi=azideg*2*pi/360;
{analytic}
end

function [srrele, sttele, srtele, xele, yele] = bsa_fem(Gmat, Sx, Sy, Sz_, Sxy, Syz, Sxz, Gpp, Pmud, Gtc, Gec, Gr, polardeg, azideg, rmesh, thmesh)
    amatte = Gmat/10^6;
    Gsxi=(Sx-Gpp)*10^6; Gsyi=(Sy-Gpp)*10^6; Gszi=(Sz_-Gpp)*10^6;
    Gsxyi=Sxy*10^6; Gsyzi=Syz*10^6; Gsxzi=Sxz*10^6;
    Gfp=0; if ~isnan(Pmud), Gfp=(Pmud-Gpp)*10^6; end
    Gpol=polardeg*2*pi/360; Gazi=azideg*2*pi/360;
{lines(465, 491)}
{fem}
end

function [rbbo, thetabbo] = bsa_bbo(Gucs, Gfri, thetaop, rop, Sp1op, Sp3op)
{bbo}
end
"""
(ROOT / "tools" / "gen_reference_borehole.m").write_text(m, encoding="utf-8")
print("wrote tools/gen_reference_borehole.m")
