"""Builds tools/gen_reference_hydroshear.m: the computation parts of polygonGroup.m and
stereonetGroup.m are sliced verbatim (line ranges) and wrapped as functions; the small
helpers (strSort, Pcm_cal, Pco_cal, Pc_cal2, dPcdz_cal, optJD) are called directly.

    python tools/make_reference_hydroshear_m.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def lines(name: str, a: int, b: int) -> str:
    src = (ROOT / "src" / name).read_bytes().decode("cp949", errors="replace").splitlines()
    return "\n".join(src[a - 1:b])


poly = lines("polygonGroup.m", 6, 84)
stereo = lines("stereonetGroup.m", 7, 103)

m = f"""% AUTO-GENERATED by tools/make_reference_hydroshear_m.py - do not edit.
% Run from repo root:  matlab -batch "run('tools/gen_reference_hydroshear.m')"
root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(root, 'src'));
out = struct();
% cases: Sv SHmax Shmin SHmax_azi(deg) phi(deg) rho_r rho_f alpha
C = [30 40 25 0 30 2600 1000 0.5;
     30 45 20 60 35 2650 1000 0.3;
     30 28 20 120 30 2500 1050 0.5;
     30 50 32 30 25 2700 1000 0.7];
J = [75.285858 151.938677; 60.189236 23.554691; 65.528164 174.726243; 33.26572 153.418764; 0 0; 90 45; 45 270];
for k = 1:size(C, 1)
    c = C(k, :);
    Svmag = c(1)*1e6; SHmaxmag = c(2)*1e6; Shminmag = c(3)*1e6; SHmaxazi = c(4)*pi/180; phi = c(5)*pi/180;
    rho_r = c(6); rho_f = c(7); alpha = c(8);
    S123 = strSort(Svmag, SHmaxmag, SHmaxazi, Shminmag);
    Pcm = Pcm_cal(S123(1,1), S123(3,1), phi);
    Pco = Pco_cal(Pcm, alpha, S123(3,1));
    [t1, t2] = optJD(S123, phi);
    Pc = zeros(size(J,1),1); grad = zeros(size(J,1),1);
    for i = 1:size(J,1)
        Pc(i) = Pc_cal2(J(i,1)*pi/180, J(i,2)*pi/180, S123, phi);
        grad(i) = dPcdz_cal(rho_r, J(i,1)*pi/180, J(i,2)*pi/180, S123, Svmag, phi);
    end
    [x, y, kcm, kco, pro_pco, pro_down] = hs_polygon(phi, Svmag, rho_r, rho_f, alpha, 1, 1);
    [kc, pp_gr, sx, sy, p, prob] = hs_stereonet(S123, Svmag, phi, rho_r, rho_f, alpha, 1);
    out.cases(k).inputs = c; out.cases(k).joints = J;
    out.cases(k).S123 = S123; out.cases(k).Pcm = Pcm; out.cases(k).Pco = Pco;
    out.cases(k).opt1 = t1; out.cases(k).opt2 = t2; out.cases(k).Pc = Pc(:)'; out.cases(k).grad = grad(:)';
    out.cases(k).poly_x = x; out.cases(k).poly_y = y; out.cases(k).kcm = kcm; out.cases(k).kco = kco;
    out.cases(k).pro_pco = pro_pco; out.cases(k).pro_down = pro_down;
    si = 1:20:361; sj = 1:10:91;
    out.cases(k).si = si-1; out.cases(k).sj = sj-1;
    out.cases(k).kc = kc(si, sj); out.cases(k).pp_gr = pp_gr(si, sj); out.cases(k).sx = sx(si, sj); out.cases(k).sy = sy(si, sj);
    out.cases(k).p = p(:)'; out.cases(k).prob = prob(:)';
    fprintf('case %d: Pcm %.4f Pco %.4f opt %s %s prob(end) %.4f\\n', k, Pcm/1e6, Pco/1e6, t1, t2, prob(end));
end
f = fullfile(root, 'tests', 'reference', 'hydroshear_matlab.json');
fid = fopen(f, 'w'); fwrite(fid, jsonencode(out), 'char'); fclose(fid);
fprintf('wrote %s\\n', f);

function [x, y, kcm, kco, pro_pco, pro_down] = hs_polygon(phi, Svmag, rho_r, rho_f, alpha, PcoCheck, probDownCheck)
{poly}
end

function [kc, pp_gr, x, y, p, prob] = hs_stereonet(S123, Svmag, phi, rho_r, rho_f, alpha, PcCheck)
{stereo}
end
"""
(ROOT / "tools" / "gen_reference_hydroshear.m").write_text(m, encoding="utf-8")
print("wrote tools/gen_reference_hydroshear.m")
