"""Builds tools/gen_reference_stereonet.m from the original stereoProjection.m helpers.
Blocks that live inside GUI callbacks (pole-density contour, designated-set mean
direction, strike list of the rose diagram, great-circle geometry) are sliced verbatim
between unique marker lines; the small helper functions are called directly.

    python tools/make_reference_stereonet_m.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read(name: str) -> list[str]:
    return (ROOT / "src" / name).read_bytes().decode("cp949", errors="replace").splitlines()


def slice_between(lines: list[str], start: str, end: str, extra_after: int = 0, start_occurrence: int = 1,
                  end_occurrence: int = 1) -> str:
    starts = [i for i, l in enumerate(lines) if start in l]
    i0 = starts[start_occurrence - 1]
    ends = [i for i in range(i0, len(lines)) if end in lines[i]]
    i1 = ends[end_occurrence - 1] + extra_after
    return "\n".join(lines[i0:i1 + 1])


sp = read("stereoProjection.m")
contour = slice_between(sp, "vec = zeros(2*size(jData,1), 3);", "[x(j+1, i+1), y(j+1, i+1)] = convert_TPCoor", extra_after=2)
contour = contour.replace("if get(handles.contour,'Value') == 1", "% (GUI if removed)").replace("points.Visible = 'off';", "% (no GUI)")
# dist3.m uses 'for i=1:size(data)' (non-scalar colon operand), which errors on MATLAB >= R2023;
# it is the plain Euclidean distance, inlined here.
contour = contour.replace("dis = dist3(vec, tmp);", "dis = sqrt(sum((vec - tmp).^2, 2));  % == dist3(vec, tmp)")
meand = slice_between(sp, "tmp = [];", "avg = avg/norm(avg);", extra_after=2, start_occurrence=1, end_occurrence=2)
# the block ends with the 'end' of the else branch and the 'end' of the outer if
rose = slice_between(read("roseDiagram.m"), "strike(2*size(didData, 2)) = 0;", "theta = (90*ones")
wc = slice_between(read("wulffCircle.m"), "N = 50;", "y = -y;", extra_after=1)  # through the end of the .if upper. block

m = f"""% AUTO-GENERATED by tools/make_reference_stereonet_m.py - do not edit.
% Run from repo root:  matlab -batch "run('tools/gen_reference_stereonet.m')"
root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(root, 'src'));
D = dlmread(fullfile(root, 'src', 'stereo_exmapledata', 'exampleData.txt'), '\\t', 1, 0);
jData = num2cell(D);
out = struct(); out.data = D;
combos = [0 0; 0 1; 1 0; 1 1];   % upper, equalAngle
for k = 1:4
    upper = combos(k,1); equalAngle = combos(k,2);
    tre = D(:,2)*pi/180 + pi; plu = 0.5*pi - D(:,1)*pi/180;
    [x, y] = convert_TPCoor(tre', plu', upper, equalAngle);
    out.proj(k).upper = upper; out.proj(k).equalAngle = equalAngle; out.proj(k).x = x(:)'; out.proj(k).y = y(:)';
    [cx, cy, res] = sp_contour(jData, upper, equalAngle);
    out.proj(k).cx = cx; out.proj(k).cy = cy; out.proj(k).density = res;
    fprintf('proj %d: density max %.3f\\n', k, max(res(:)));
end
% convert_VecTP on the pole vectors of the data (as in FCM_Callback)
tre = D(:,2) + 180; tre(tre >= 360) = tre(tre >= 360) - 360; plu = 90 - D(:,1); plu(plu < 0) = plu(plu < 0) + 360;
V = [cos(plu/180*pi).*cos(tre/180*pi), cos(plu/180*pi).*sin(tre/180*pi), sin(plu/180*pi)];
[vt, vp] = convert_VecTP(V(:,1), V(:,2), V(:,3));
out.vec = V; out.vec_tre = vt(:)'; out.vec_plu = vp(:)';
% great circles (wulffCircle geometry) for 5 planes, lower and upper
P = [30 45; 60 120; 85 200; 10 300; 45 0];
for i = 1:5
    for upper = 0:1
        [gx, gy] = sp_wulff(P(i,1)*pi/180, P(i,2)*pi/180, upper);
        out.gc(i, upper+1).dip = P(i,1); out.gc(i, upper+1).did = P(i,2); out.gc(i, upper+1).upper = upper;
        out.gc(i, upper+1).x = gx; out.gc(i, upper+1).y = gy;
    end
end
% designated-set windows: treFrom treTo pluFrom pluTo (deg)
W = [150 220 10 40; 330 30 0 30; 100 200 -20 30; 0 360 0 90];
for i = 1:size(W,1)
    [avg, n] = sp_meand(jData, W(i,1)*pi/180, W(i,2)*pi/180, W(i,3)*pi/180, W(i,4)*pi/180, 0, 0);
    out.sets(i).window = W(i,:); out.sets(i).avg = avg; out.sets(i).n = n;
    if any(isnan(avg)), out.sets(i).dip = NaN; out.sets(i).did = NaN;
    else
        [ta, pa] = convert_VecTP(avg(1), avg(2), avg(3)); di = pi/2 - pa; did = ta - pi; if did < 0, did = did + 2*pi; end
        out.sets(i).dip = di*180/pi; out.sets(i).did = did*180/pi;
    end
    fprintf('set %d: n=%d dip %.2f did %.2f\\n', i, n, out.sets(i).dip, out.sets(i).did);
end
% FCM from a fixed initial partition
rng(7); U0 = initfcm(3, size(V,1));
[center, U, obj] = sp_fcm(V, U0, 3);
out.fcm.U0 = U0; out.fcm.center = center; out.fcm.U = U; out.fcm.obj = obj(:)';
fprintf('fcm: %d iterations, obj %.6f\\n', numel(obj), obj(end));
% rose diagram counts
[theta] = sp_rose(D(:,2)');
f = figure('visible', 'off'); [tout, rout] = rose(theta, 36); close(f);
out.rose_theta = theta(:)'; out.rose_counts = rout(2:4:end);
fo = fullfile(root, 'tests', 'reference', 'stereonet_matlab.json');
fid = fopen(fo, 'w'); fwrite(fid, jsonencode(out), 'char'); fclose(fid);
fprintf('wrote %s\\n', fo);

% =====================================================================
function [x, y, result] = sp_contour(jData, upper, equalAngle)
{contour}
end

function [avg, n] = sp_meand(jData, treFrom, treTo, pluFrom, pluTo, upper, equalAngle)
    fig = figure('visible', 'off'); axes(fig); hold on;
    handles.hg.radiobutton2 = uicontrol(fig, 'style', 'radiobutton', 'Value', 0);
    handles.hg.listbox2 = uicontrol(fig, 'style', 'listbox');
    hWindow = cell(1); list_desig = [];
{meand}
    n = size(tmp, 1);
    close(fig);
end

function theta = sp_rose(didData)
{rose}
end

function [x, y] = sp_wulff(di, did, upper)
{wc}
end

function [center, U, obj_fcn] = sp_fcm(data, U, cluster_n)
    expo = 2; max_iter = 100; min_impro = 1e-5;
    obj_fcn = zeros(max_iter, 1);
    for i = 1:max_iter
        [U, center, obj_fcn(i)] = stepfcm_new(data, U, cluster_n, expo);
        if i > 1
            if abs(obj_fcn(i) - obj_fcn(i-1)) < min_impro, break; end
        end
    end
    obj_fcn(i+1:max_iter) = [];
end
"""
(ROOT / "tools" / "gen_reference_stereonet.m").write_text(m, encoding="utf-8")
print("wrote tools/gen_reference_stereonet.m")
